### ISSUE TITLE
#Tasks not visible while all other Tags are

### ISSUE THREAD

**Issue by blogbourri** [logseq/db-test#10]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

after assigning #task to a block, it doesn't display anywhere that the block is a task. this is at odds with how other tags work. it also makes it impossible to remove that tag after it has been added to a block.

### Reproduce the Bug

1. type some text
2. type "#Task" and hit enter
3. the tag is assigned to the block (the block shows up as a tagged node), but the tag doesn't display like other tags would

### Expected Behavior

"#Task" should appear on the right, just like other tags currently do. it should also be removable like other tags.

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by blogbourri** [comment]
i think since the call (# hashtag) and apparent result (adding block properties to the block) are the same as all other tags, there should be some sort of feedback within logseq explaining the uniqueness of #task if it is intended (which it very well seems to be) -- although my preference would be for it to not be a unique class tbh and have it be consistent with other tags in both function and appearance

**Comment by tiensonqin** [comment]
#task will be displayed when hovering the block.
The goal is to make the UI clean because #task could be used frequently. We might introduce a property so that people can configure it to always be displayed or create other tags like #task.

**Comment by blogbourri** [comment]
i think #task visible on hover is still a bit idiosyncratic. especially because when you assign a second tag, the behavior goes away and it's always visible. i think having it just default follow the behavior of the other tags is the move, personally.

**Comment by blogbourri** [comment]
https://github.com/user-attachments/assets/f16d018b-25a2-47d2-a3d6-6575cf7790da
