### ISSUE TITLE
Tagging page inline differs between new & existing pages

### ISSUE THREAD

**Issue by nckre** [logseq/db-test#100]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Tagging a page inline feels very inconsistent, parts of this might be buggy:

1. New page + tag w/o space (e.g. `[[Logseq]]#Organization`) → Only new page is created w/o tag
2. Existing page + tag w/o space (e.g. `[[Logseq]]#Organization`) → Page is tagged
3. New or existing page + space + tag → (e.g. `[[Logseq]] #Organization`) Only node is tagged, page is not tagged
4. New or existing page + tag inside reference (e.g. `[[Logseq #Organization]]`) → tag not applied

### Reproduce the Bug

1. Create a new page and tag it inline (e.g. `[[Logseq]]#Organization`)
2. Go to page and see that tag is not applied

Do the same for an existing page and see that tag is applied.

### Expected Behavior

All of the above 4 use cases should have the same behaviour, the tag should be applied to the page.

I think only (3) is debatable, but if there is no other content but a page reference and a space, it is weird that the node is tagged.

### Screenshots

![CleanShot 2024-09-17 at 14 32 15](https://github.com/user-attachments/assets/0a53f063-bcaf-4b93-9600-9d6cfd9e86ea)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by logseq-cldwalker** [comment]
Hi. A fix for the first case should be up on test.logseq.com in ~10m. Behaviors for 2-4 are correct. For 4, you should get a warning since '#' is not allowed in a page name

**Comment by logseq-cldwalker** [comment]
Closing as bugs we wanted to fix have been fixed
