### ISSUE TITLE
Rename `Delete property` to `Remove property`

### ISSUE THREAD

**Issue by nckre** [logseq/db-test#101]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

The dropdown menu for properties reads `Delete property` but after using it, the property is still available in the graph.

![CleanShot 2024-09-17 at 15 53 03@2x](https://github.com/user-attachments/assets/7e2bcf4b-5295-4c33-8612-6f9911018cd3)

It should rather say `Remove property` or `Remove property from tag`.

### Reproduce the Bug

1. Add property to tag
2. Click on property

### Screenshots

![CleanShot 2024-09-17 at 14 43 58](https://github.com/user-attachments/assets/3fa210f6-029b-4689-a0fd-5a0bf9f7e2ea)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by logseq-cldwalker** [comment]
Hi. Agree that language is ambiguous. Pushed up a fix to test which will be up on ~10m
