### ISSUE TITLE
File name and link disappears in preview during upload

### ISSUE THREAD

**Issue by Zhehan-Z** [logseq/db-test#102]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

While files are being uploaded to the server, there is no progress bar. Move cursor focus away from the line, and the line seems as if it is empty. After file upload finishes, the filename appears.

### Reproduce the Bug

1. Paste or drag a file into the editor.
2. Wait for file to upload, and in the meantime move cursor away from the line containing file link
3. File link apparently disappears

### Expected Behavior

An upload progress bar is welcome. It should take the spot of the link while the file is being uploaded.

### Screenshots

![CleanShot 2024-09-17 at 22 58 27@2x](https://github.com/user-attachments/assets/8f668b32-30b2-49ba-8e4c-03f748e90f64)
![CleanShot 2024-09-17 at 22 59 57@2x](https://github.com/user-attachments/assets/e55a7b83-539a-45ea-9dda-493914ee22b3)

### Browser, Desktop or Mobile Platform Information

OS: macOS Sonoma 14.4 (23E214)
Browser: Safari 17.4 (19618.1.15.11.12)
Logseq DB: 0.10.10

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
Fixed by https://github.com/logseq/logseq/commit/46dd9e355025a32b6e015d169a59ea1e2a74600b.
