### ISSUE TITLE
Pasting differently formatted dates disappear after entry

### ISSUE THREAD

**Issue by kerim** [logseq/db-test#103]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

My MD database has dates in this format: [[2026-07-31]]

If I paste this into a block in the DB viersion, it simply disappears after exiting edit mode. 

### Reproduce the Bug

Paste [[2026-07-31]] into a block

### Expected Behavior

Ideally, it would recognize that this is a date and convert it to the new date format used in the DB version, or else it should at least keep the block as it was.

### Additional Context

I earlier reported a lot of errors during import from the MD version, now I wonder if the fact that I use a custom date format might be one of the causes for those errors?

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
@kerim I just pushed a fix, the website will be updated in 10m.

**Comment by kerim** [comment]
I can confirm that this is working now. Thanks!
