### ISSUE TITLE
Date picker UI not updating when using keyboard

### ISSUE THREAD

**Issue by nckre** [logseq/db-test#104]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When opening the date picker, can control the date with keyboard shortcuts but the highlight on the date is not updating.

![CleanShot 2024-09-18 at 12 20 35](https://github.com/user-attachments/assets/16ea09b1-6b3d-412e-aa5a-8c3c13e12a4f)

### Reproduce the Bug

1. Open date picker
2. Use "Arrow right" to move to tomorrow
3. Hit enter

### Expected Behavior

Highlight should always be on selected date.

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
@nckre Which browser are you using? I tried but failed to reproduce it.
https://www.loom.com/share/e1ce175ba0be4411985204b137ed1434

**Comment by nckre** [comment]
Interesting. Originally tested in Arc Browser (MacOS), but can see it in Chrome (ver 129.0.6668.59) too:

![CleanShot 2024-09-18 at 17 57 31](https://github.com/user-attachments/assets/9baae9f1-07b0-4b00-bfc3-07a88ad700d2)

**Comment by tiensonqin** [comment]
@xyhp915 Any ideas?

**Comment by tiensonqin** [comment]
Interesting one, I can reproduce this on Arc 1.60.0.

**Comment by tiensonqin** [comment]
@nckre I just pushed a fix, let me know whether it works for you. The website should be ready.

**Comment by nckre** [comment]
Yep, seems fixed, can see the highlight now in Arc
