### ISSUE TITLE
Pages starting with hashtag have hidden header

### ISSUE THREAD

**Issue by nckre** [logseq/db-test#106]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

You cannot create a page that starts with a hashtag inline (see https://github.com/logseq/db-test/issues/105) but there are two ways to create a page like `[[#Organization]]:

1. Rename existing page
2. Edit page reference inline and click out of text 

Pages that start with a hashtag have their header hidden.

If the page has a space, only the beginning is hidden.

If the hashtag is existing elsewhere, it's displayed as a link.

### Reproduce the Bug

1. Go to existing page
2. Edit header and add hashtag at the beginning
3. See page again

### Screenshots

![CleanShot 2024-09-18 at 12 37 01](https://github.com/user-attachments/assets/e58c80e8-03e0-4d5d-b576-296d4261938c)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by nckre** [comment]
@tiensonqin still cannot see the header of a page I had created earlier, but can't create new pages with hashtag any more - so I guess we consider it fixed?

**Comment by tiensonqin** [comment]
@nckre Yes, old pages with hashtags are not fixed.
