### ISSUE TITLE
Task status changes are automatically reverted by sync

### ISSUE THREAD

**Issue by Zhehan-Z** [logseq/db-test#107]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When the user tries to change a task's status to 'DONE' or any other option, the edit is automatically reverted the moment sync begins working. This makes directly editing task status in a synced DB impossible, and unfortunately breaks the whole workflow.

### Reproduce the Bug

1. Create a task in a **synced** DB.
2. Click to mark the task as DONE (or just choose any option from the dropdown, all reproducible).
3. The DONE icon stays for only a second, and then flickers back to the original TODO state.
4. Observe how the indicator next to the cloud icon in the menu bar change from green to yellow, and back to green while this happens.

### Expected Behavior

The status change should be correctly registered and accepted by the sync server.

### Screenshots

![CleanShot 2024-09-18 at 20 48 27](https://github.com/user-attachments/assets/89196309-aef8-4295-b07b-0fb896780fb5)

### Browser, Desktop or Mobile Platform Information

OS: macOS Sonoma 14.4 (23E214)
Browser: Safari 17.4 (19618.1.15.11.12)
Logseq DB: 0.10.10

### Additional Context

Every time the sync operation that reverts the edit happens, a new line appears in the console log:

[Log] rtc/apply-remote-ops-log (db-worker.js, line 880)

No other lines appear, and no further information after expanding that entry.

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
@Zhehan-Z lol, the RTC is not ready for testing yet, but thank you for letting us know!

**Comment by nckre** [comment]
@tiensonqin I noticed this too there was no announcement but seems that account creation was unlocked and works:

![CleanShot 2024-09-18 at 18 05 50@2x](https://github.com/user-attachments/assets/eaafe454-cf21-4f16-9dc3-f2af561096a0)

Should we try this or not?

**Comment by Zhehan-Z** [comment]
Current quick workaround: after the change gets reverted, immediately change status to No Status. Then the correct status shows up and gets synced. No idea why that might work.

**Comment by Zhehan-Z** [comment]
> @Zhehan-Z lol, the RTC is not ready for testing yet, but thank you for letting us know!

So the whole ‘sync’ function is not yet ready for testing? Or it’s just the RTC toggle?

**Comment by RCmerci** [comment]
this bug has been fixed. 
we'll open testing rtc later(no specific date yet).
> So the whole ‘sync’ function is not yet ready for testing? Or it’s just the RTC toggle?
sync for db-version is not ready for testing now
