### ISSUE TITLE
Can create graphs with `/` in name

### ISSUE THREAD

**Issue by nckre** [logseq/db-test#109]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When trying to create a graph with special symbols (e.g. `#`) an error message shows up showing all forbidden characters.

![CleanShot 2024-09-19 at 10 48 26@2x](https://github.com/user-attachments/assets/47b44f27-e545-4372-a9d1-aba8f75dd6e3)

However, can create graphs with forward slash (only symbol that worked from the list):

![CleanShot 2024-09-19 at 10 49 38@2x](https://github.com/user-attachments/assets/70023aca-6cce-4ec8-848d-7e4641587fe5)

### Reproduce the Bug

1. Go to `Create new db graph`
2. Create graph with forward slash in name (e.g. `test/test`)

### Expected Behavior

Either remove `/` from list of forbidden characters or block creation of graphs with forward slash in name

### Screenshots

![CleanShot 2024-09-19 at 10 46 51](https://github.com/user-attachments/assets/bcf99091-2d19-4756-afbf-02acfe84f804)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by nckre** [comment]
Seems like `/` is automatically renamed to `_` but still shows up in the graph name:

![CleanShot 2024-09-19 at 11 11 39@2x](https://github.com/user-attachments/assets/7bb4c3e6-f6ae-4646-a0ea-0e3a8bb4049b)

**Comment by tiensonqin** [comment]
Fixed by https://github.com/logseq/logseq/commit/5da1e920bf96a7c3898a70d5c19f796639b2ef77.
