### ISSUE TITLE
Embedded Youtube player too narrow

### ISSUE THREAD

**Issue by nckre** [logseq/db-test#110]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When embedding a youtube video, the player is quadratic and looks very narrow compared to the MD version.

DB Version

![CleanShot 2024-09-19 at 11 14 33@2x](https://github.com/user-attachments/assets/1be20d82-7ddb-4780-bb0c-da00e3343ff1)

MD Version 

![CleanShot 2024-09-19 at 11 15 37@2x](https://github.com/user-attachments/assets/c5eff15c-ea67-4d6e-9f6d-20168d2c85f4)

### Reproduce the Bug

1. Create node with youtube link (e.g. `https://www.youtube.com/watch?v=8NJ2xpCx0vY&t=9s`)

### Screenshots

![CleanShot 2024-09-19 at 11 13 08](https://github.com/user-attachments/assets/b6831cad-bce9-499a-9da5-544a29ec0c93)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
Fixed by https://github.com/logseq/logseq/commit/599475b15e72845a1fc57f43d35d75d19ef8e873.

**Comment by cannibalox** [comment]
@tiensonqin 
maybe it could look better with a 16/9 aspect ratio ? (to avoid the squeezed aspect ratio on the thumnail) ?
![image](https://github.com/user-attachments/assets/ca921cf1-e741-46a7-99be-aa0cb45ee89e)
either with css aspect-ratio or by embedding the iframe in absolute pos inside a div with padding like this  : https://www.h3xed.com/web-development/how-to-make-a-responsive-100-width-youtube-iframe-embed

**Comment by tiensonqin** [comment]
@cannibalox Done! https://github.com/logseq/logseq/commit/4477dcfb95eefe7f47895720eec6f2ae2ceca501.

**Comment by cannibalox** [comment]
@tiensonqin thanks, the embed has the aspect ratio, but follows the default youtube 512x315px, maybe this
```
.aspect-video {
    aspect-ratio: 16/9;
    width: 100%;
    height: auto;
}
```
would use full width ? linking to  #188
