### ISSUE TITLE
Setting codeblocks to readonly prevents modifying config.edn 🤦‍♂️

### ISSUE THREAD

**Issue by Bad3r** [logseq/db-test#112]
### What Happened?

this issue is a limitation due to using CodeMirror as the only way to edit config.edn in the db version.

Once codemirror is set to readonly there is no way to edit config.edn to reset the setting 🤦‍♂️ in the MD version it was possible to just edit the text file.

### Reproduce the Bug

1. Navigate to config.edn from settings
2. modify codemirror options to enable readonly mode:
```edn
 :editor/extra-codemirror-options
 {:lineWrapping  true  ; Default value: false
 :lineNumbers    true  ; Default value: true
 :readOnly       true} ; Default value: false
```
3. Now its impossible to reset it

**Comment by Bad3r** [comment]
Ok I was able to fix it by exporting the DB and editing it with DB Browser for SQLite

![](https://media1.tenor.com/m/mqBYbQHsqUcAAAAC/phew-dogs.gif)

**Comment by tiensonqin** [comment]
"config.edn" has been updated to be able to be edited with the "readOnly" option.
