### ISSUE TITLE
Referenced or Macro Query Table UX issue

### ISSUE THREAD

**Issue by hdansou** [logseq/db-test#116]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When a query node is referenced or is created from a macro, the table shrinks and sometimes, we can't toggle between the Table view and List view

### Reproduce the Bug

Scenario one
1. Create a Query node
2. copy the node ref
3. Paste in another node

Scenario two
1. Create a macro config ``"find-keyword-in-page" "{{query (and \"$1\" [[$2]])}}"}`
2. Create a node with the macro query `{{{find-keyword-in-page plugin,logseq}}}`

### Expected Behavior

Referenced query table should render the full table

### Screenshots

https://github.com/user-attachments/assets/ac46a74f-8d9e-4bb6-982f-43737742fd93

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by logseq-cldwalker** [comment]
Hi. Using macros to create queries is not possible in the db version as queries can't be triggered only by text. Feel free to create a discord feedback thread if you'd like a similar feature to exist. If we did build something like this in the db version, hopefully it'd be more visual and user friendly
