### ISSUE TITLE
Reordering properties issue

### ISSUE THREAD

**Issue by cannibalox** [logseq/db-test#117]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

reordering properties is unreliable : values get mixed up (probably a display refresh issue), see gif below
![ss_Maxthon_more_-_Maxthon_20240919_B7Rzoa6aLf](https://github.com/user-attachments/assets/a41bc62b-e09e-4192-a242-0e29ec0800e9)
note how `occupation:: virologist` becomes `occupation:: umbrella corp` as I move the property up or down

### Reproduce the Bug

create several properties with text values, re-order the properies using mouse drag. 
BTW, it would be nice and consistent if the keyboard shortcut to move blocks up/down would also work to move properties up/down  .

### Browser, Desktop or Mobile Platform Information

win 11
vivaldi browser

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
Fixed by https://github.com/logseq/logseq/commit/38e2e14d0751d25ede1dcc135979c890bfdb5db3.
