### ISSUE TITLE
Renaming existing pages to dates breaks Journals

### ISSUE THREAD

**Issue by nckre** [logseq/db-test#118]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When using the date picker or writing a date inline (e.g. `[[Sep 20th, 2024]]`), this page is created as a Journal.

When renaming an existing page to a date (e.g. `[[Hello]]` -> `[[Sep 18th, 2024]]`), this page is not part of the Journal.
After creating the same page from date picker, there are now 2 pages with the same title, but the date does not show up in `Journals`

### Reproduce the Bug

1. Go to a page
2. Rename the page to a date e.g. `[[Sep 20th, 2024]]`
3. Reload `Journals` and see that date is not visible

### Screenshots

![CleanShot 2024-09-21 at 10 00 41](https://github.com/user-attachments/assets/009cdfd6-a320-4a8b-b28d-222c1b74007c)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by nckre** [comment]
The renaming also works for existing dates (e.g. can do `[[Hello]]` -> `[[Sep 21st, 2024]]`) so that there are two pages with the dates - but if the "real" date page was created earlier, the `Journal` seems to work fine.

**Comment by tiensonqin** [comment]
Thank you for the report!
Journal pages are particular in our current implementations, they have pre-assigned IDs compared to regular pages. 
I've updated the code to disallow renaming a page to a journal date.
