### ISSUE TITLE
Task icon smaller than emoji

### ISSUE THREAD

**Issue by hdansou** [logseq/db-test#12]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Task icons are small do not look aligned with the emojis

### Reproduce the Bug

Create a task block that has tags(these tags have multi values, and each value has emojis).
When the emojis are rendered when placed at the beginning of the blog, they are bigger.

### Expected Behavior

Make task icon the same size as emojis

### Screenshots

![image](https://github.com/user-attachments/assets/807a988d-12ad-4ee8-bcae-b9b7e21619c7)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
Fixed.
