### ISSUE TITLE
Delete datetime property value from calendar like in date calendar

### ISSUE THREAD

**Issue by hdansou** [logseq/db-test#123]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

After adding a datetime type, there is no way to remove the set datetime

### Reproduce the Bug

1. create a property with datetime
2. create a node with the datetime property
3. set a datetime value
4. try to remove the datetime previously set

### Expected Behavior

Ability to remove datetime from a property, similar to the date picker. 
![image](https://github.com/user-attachments/assets/6abf6f34-67e3-42a3-bb83-75df7a42f794)

It would also be nice if the date can be removed without relying on the mouse.

### Screenshots

![image](https://github.com/user-attachments/assets/de40721d-515a-4c79-9e01-de097fae18ba)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by logseq-cldwalker** [comment]
Hi. Agree this would be nice. In the meantime, any property value can be deleted by clicking on a block's property to open a menu and selecting `Delete property from node`. Currently the text is wrong but I'll fix that shortly. You can also activate the menu from the keyboard when on a node by using `Cmd-j` as described in https://github.com/logseq/docs/blob/feat/db/db-version.md#property-shortcuts

**Comment by logseq-cldwalker** [comment]
This should be done and up on test.logseq.com in ~10m
