### ISSUE TITLE
Query Table column not resizable

### ISSUE THREAD

**Issue by hdansou** [logseq/db-test#124]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

A Tag table column can be resized but not the Query table

### Reproduce the Bug

Create a query table
Attempt to resize a column by clicking on the column edge and dragging to resize.

### Expected Behavior

Ability to resize a column size

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by logseq-cldwalker** [comment]
This should now be fixed on test.logseq.com
