### ISSUE TITLE
CMD+(shift)k does not navigate to block

### ISSUE THREAD

**Issue by Bad3r** [logseq/db-test#125]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

in a page with multiple blocks attempting to navigate to a specific block utilizing search graph or search page `CMD+(shift)k` does not navigate to the target block. 

### Reproduce the Bug

1. create a page with multiple blocks 
	a. should have paging/many blocks
2. use `CMD+(shift)k` to search and navigate to a specific block

Example graph containing one page [[test]] with 100 lines.

github doesn't allow uploading .sql
https://gofile.io/d/JiFfFt

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
@Bad3r The bug should be fixed, you can give it a try in 10 minutes.

**Comment by Bad3r** [comment]
> @Bad3r The bug should be fixed, you can give it a try in 10 minutes.

Just tested and can confirm it's fixed :pray: 
Thank you! This is an essential feature of Logseq that makes using it much better.
