### ISSUE TITLE
new codeblock type block does not allow for specifying a language

### ISSUE THREAD

**Issue by Bad3r** [logseq/db-test#127]
steps to reproduce
1. Use the /codeblock command
2. No way to edit the language for the codeblock in view or edit mode
4. Compare to manually creating a codeblock using \`\`\`

![image](https://github.com/user-attachments/assets/cab7ab03-5bf4-49c8-8926-9c29b216d05b)

**Comment by logseq-cldwalker** [comment]
Hi. We're aware of this and should be addressing this soon

**Comment by logseq-cldwalker** [comment]
This should be up on test.logseq.com in ~10m
