### ISSUE TITLE
Comments in /codeblock are treaded as a header

### ISSUE THREAD

**Issue by Bad3r** [logseq/db-test#128]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

If a /codeblock contains the char `#` logseq shows an error:
![image](https://github.com/user-attachments/assets/13edf90a-081c-4869-b96c-5d43291ab85f)

### Reproduce the Bug

1. create a codeblock via the command /codeblock
2. Add a string in line 1
3. In line 2 add a `#` followed by a string
```
line1
# line2
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by logseq-cldwalker** [comment]
Hi. Thanks for noticing this. I was also able to reproduce this bug in our :math and :quote display types. This should be fixed on test in ~10m.
