### ISSUE TITLE
Text Property set to show on the right side are wrapped

### ISSUE THREAD

**Issue by hdansou** [logseq/db-test#13]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

A text property with the work `icebox` is wrapped when placed on the right side of the page.

### Reproduce the Bug

* Create Class with a property with text value
* Place its value on the right side of the block
* 

### Expected Behavior

The length of the property should be more than five characters.
Ideally, it would be nice to have a setting to control the length.

### Screenshots

![image](https://github.com/user-attachments/assets/4f3051e7-3080-4996-aba6-e574768c9688)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
@hdansou Can you still reproduce this bug on the latest website?

**Comment by hdansou** [comment]
> @hdansou Can you still reproduce this bug on the latest website?

This is resolved. Thank you @tiensonqin
