### ISSUE TITLE
A reference to a block containing a header and tag does not display correctly

### ISSUE THREAD

**Issue by Bad3r** [logseq/db-test#130]
### What Happened?

If a block contains a header and a tag e.g.:
```
- ### Block1 #tag1
```
when its referenced it will display the header tags:
![image](https://github.com/user-attachments/assets/be56603b-acf5-4e50-be54-71a326c7a773)

Steps to reproduce:
1. create a block with a header and a tag
```
- ### Block1 #tag1
```
2. create a reference to the block
3. Notice the reference contains the header tags e.g `###`

**Comment by tiensonqin** [comment]
Fixed by https://github.com/logseq/logseq/commit/61d91bd16d373064a2d4111eca4a97e3246c8d59.
