### ISSUE TITLE
Graph search does not work as expected

### ISSUE THREAD

**Issue by Bad3r** [logseq/db-test#132]
### What Happened?
Is there a plan to implement fuzzy matching for search? 
search currently does not work as expected. For example, searching for a block containing:
```
[[link]] Test
```
with 
```
link Test
```
will not return the expected result.
you must search for the exact string with the square brackets.

There is also #125 which is more UI related.

**Comment by tiensonqin** [comment]
Fixed by https://github.com/logseq/logseq/commit/3f75a215678f6ded8457ea65de4bd194ea38c614.
