### ISSUE TITLE
linked references in property values are not recognized properly after import

### ISSUE THREAD

**Issue by cannibalox** [logseq/db-test#134]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

tried to import a medium-sized graph (4K files resulting in 40K pages).
once MD pages are imported, the [[page-refs]] are not parsed correctly:

* the graph is heavily connected and the graph view 'sees' the links
![ss_Maxthon_Graph_-_Maxthon_20241007_l3LsqWF2mP](https://github.com/user-attachments/assets/59f546bb-92af-4358-b45b-4c9aec8e323f)
![ss_Maxthon_Graph_-_Maxthon_20241007_CckPSdDMHd](https://github.com/user-attachments/assets/dfe66825-c8e4-41e2-a344-6a597e0463a4)

* but, actually `All page`s show 0-1 backlinks. 
![ss_20241006_I7-1355_vl3J4jJQTf](https://github.com/user-attachments/assets/029ec887-0897-439b-989a-c3414e432b17)

* and individual pages that should have a lot of incoming links don't display linked refs correctly : 
![ss_Maxthon_Witness_(1985)_-_Maxthon_20241007_zDfxv1YgO0](https://github.com/user-attachments/assets/8ddee124-af68-44f8-9c4a-bfb54dc61145)

## once pages are edited, links are correctly parsed and recognized 

I need to edit the nodes/pages before the links are correctly recognized, either just adding a space or typing something (see image below, I had to add a space), only then, the backlinks start to be populated, **but only for pages/blocks where I manually triggered the edit.**
![ss_Maxthon_20,000_Leagues_Under_the_Sea_(1954)_-_Maxthon_20241005_NuerodGCj0](https://github.com/user-attachments/assets/a33813f4-bded-4bca-ad93-36843c6ac4a9)

*note that the image above also exhibit another issue where some [[links]] appear as plain text rather than proper links to nodes. I **believe** this specific issue was fixed on 2024-10-06*

it seems Luhman is experiencing [a similar issue](https://discord.com/channels/725182569297215569/1269974802471456808/1292404437003796513)

### Reproduce the Bug

to repro, here's a test graph in zip format (approx 4k movies metadata from omdb converted to md format resultin gi n40k pages) :
[ls-movies-4k.zip](https://github.com/user-attachments/files/17271417/ls-movies-4k.zip) -- note to Tienson : that's the same graph I uploaded on discord for the search issue
you can import and specify `genre` and `movies`as new tags 

next, open the All pages to see backlinks. 
try to search for `Harrison Ford`, see his page has no backlinks. Now go to `star wars: episode IV` and see page [[Harrison Ford]] is in the `actors::` values. 
now edit the "star wars" page, add a note or delete an actor then go back to [[harrison ford]] and see the updated Linked Ref.

  

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by logseq-cldwalker** [comment]
@cannibalox Hi. Could you try with the latest version of the importer? When I import a subset of your test graph that includes all of Harrison Ford's movies, I am seeing linked references for Harrison Ford's page

<img width="829" alt="Screen Shot 2024-11-25 at 4 15 32 PM" src="https://github.com/user-attachments/assets/50632e96-4b90-4606-a832-1d99a0e87f03">

**Comment by cannibalox** [comment]
weird, it's not working for me usinf build 9aff2d0 (tested on a chromium with kernel 131.0.6778.96 and official chrome 130). zero backlinks from properties.
I tried to trim the movies graph, even with the10 pages graph below, I don't see backlinks....
![image](https://github.com/user-attachments/assets/8309d649-bb68-4c17-a0f5-7e1d04636255)
[ls-movies-10.zip](https://github.com/user-attachments/files/17926850/ls-movies-10.zip)

**Comment by logseq-cldwalker** [comment]
@cannibalox Thanks for the smaller graph. I was able to reproduce. A fix should be up on test.logseq.com in ~10m

**Comment by cannibalox** [comment]
hi @logseq-cldwalker , it's **working good now**, I tried to import several graphs and all linked refs were showing up, thank you for the fix !
 
I then noticed the "page graph" seems to not see links. should I open a different GH issue or could it be a related issue ?
page graph : node is showing but no links
![image](https://github.com/user-attachments/assets/cb130cfb-ca7a-4ddf-b893-aaf8752c6ef5)
vs graph view : we see multiple links
![image](https://github.com/user-attachments/assets/b7dcc35d-4f0c-4a88-9c54-40cc569a20a0)
same for tags with lots of linked refs bu "page raph" is showing none
![image](https://github.com/user-attachments/assets/79285002-d332-4d82-afe7-54f3ac6b9dba)

**Comment by cannibalox** [comment]
another note that may be a related bug :

* In the image below, I have imported a graph with new tag`#movies`, the props are movies metadata like `year`, `actors`, etc...
* for the property `actors::`, I tried to setup a node tag `#actor` (which has properties like birth-date, etc as seen in the right sidebar), in hope that all actors listed for each #movie in the property `actors::` would then be automatically tagged as `#actor` with all the property field.  
![image](https://github.com/user-attachments/assets/d6a6c5f9-c352-45da-9ccf-30d186c10370)

is my logic flawed or is this a bug ? I think it works in a db graph where all nodes and tags are manually created, but it seems to fail for imported nodes.  (ultimately, I hope that props and tags can be interchangeable as in logseq files, as in this use-case, it would eliminate the need for creating a separate node tag)

**Comment by logseq-cldwalker** [comment]
@cannibalox Glad to hear the issue has been fixed :)

> I then noticed the "page graph" seems to not see links. should I open a different GH issue or could it be a related issue ?P

Worth opening a new issue. Would be good to mention how the page graph is working as I was unable to reproduce

> for the property actors::, I tried to "Specify node tags" : #actor (which has properties like birth-date, etc as seen in the right sidebar), in hope that all actors listed for each #movie in the property actors:: would then be automatically tagged as #actor with all the property field.

When a :node property is configured to have a tag it applies to future uses of the property and it doesn't change all existing property values. I wouldn't expect such a possibly large batch operation to occur while configuring one property. If your use case could be solved by adding batch operations to tables (which we hope to do at some point), feel free to mention it in [the batch operation thread](https://discord.com/channels/725182569297215569/1293032308026118164). If not or if you just want a separate thread, feel free to create one in `#alpha-db-feedback`
