### ISSUE TITLE
Tag Page >"Tagged notes" section should be collapsible

### ISSUE THREAD

**Issue by cannibalox** [logseq/db-test#135]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

usability concern regarding the Tagged note section : 

on #Tag pages, the sections that are under the Table view are not easily accessible when the table is big : you need to scroll through the whole table before you can add notes or see linked refs/unlinked refs sections.
When you have a lot of rows , this can take quite a long time (especially considering issues like #126)
 ![ss_Maxthon_Animation_-_Maxthon_20241007_Y77SWtRMeV](https://github.com/user-attachments/assets/3bdf7be9-0b72-4c02-bd89-074c2d7766c8)

suggestions :
    
* the Tagged Notes section should foldable
* or maybe the table container should have a max-height and be overflow-y:scrollable independently of the main windows 

### Reproduce the Bug

go to a tag page with more than 200 dense rows (you can use the graph sample provided in #134 and check the `#Sci-fi` page for instance)
try to reach the bottom of the page is less than 2 seconds

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by cannibalox** [comment]
@logseq-cldwalker  Thank you ! small addition but big improvement in my case. 

now that I can see the whole page, I wonder if sections like `Notes` and `Tag Properties` should also be foldable via the ui ?
![image](https://github.com/user-attachments/assets/7ce6fbbc-3446-4acd-8cca-57bc412197a0)

on a broader scope, maybe all the pages should conform to the same layout, with collapsible sections that enforce consistency across the whole app ? 
```
TITLE ⚙️
 >metadata/properties
 >notes
 > hierarchy
 >linked refs
 >unlinked refs
 ```

**Comment by logseq-cldwalker** [comment]
> now that I can see the whole page, I wonder if sections like Notes and Tag Properties should also be foldable via the ui ?

You can already collapse a page's properties with `cmd-;` as described in https://github.com/logseq/docs/blob/feat/db/db-version.md#nodes. Fwiw Tag Properties is a property, not a section.

Agree that making the Notes section collapsible would be consistent with other sections. I'm hesitant to do that since there is variety of use cases to support in a page's body including perf considerations. @tiensonqin Do you think it's ok to make the Notes section collapsible?

**Comment by cannibalox** [comment]
I didn't realize the page title was a foldable section for metadata, thank you :) 
the shortcut `cmd ;`  or `ctrl ;` or `ctrl alt ;` (or it 3 key `cmd-;` ?) doesn't work for me on windows ) chrome or vivaldi (win11, tested on US qwerty and French azerty keyboards). do you want a separate bug report for this ?

**Comment by logseq-cldwalker** [comment]
@cannibalox For windows I would expect it to be `Ctr+;` as it uses the same modifier as search e.g. `Ctrl+k`. You can open an issue on the main repo if you'd like though we're unlikely to take a look with focus on db version.  In the meantime, the command is [:editor/toggle-block-children](https://github.com/logseq/logseq/blob/f05d4e40d09e6defa89cebd99c51af9c21e73ee6/src/main/frontend/modules/shortcut/config.cljs#L318-L319) if you'd like to add a custom keybinding
