### ISSUE TITLE
Parent-children relationship not imported for Namespaces from File-based Graph

### ISSUE THREAD

**Issue by LER0ever** [logseq/db-test#136]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

According to the Documentation here: https://github.com/logseq/docs/blob/feat/db/db-version-changes.md#namespaces , the DB version should have namespace support as before, but it seems to only work on newly created ones, and does not respect the previously imported namespaces from file-based graphs. 

### Reproduce the Bug

1. Import a file-based graph with namespaces
2. The namespace pages does not have proper parent-child relationships, and the hierarchy is also gone
3. Create a new [[test1/test2/test3]] on the DB graph, the namespace functionality works as expected

### Expected Behavior

Namespace feature should work for both newly-created ones in DB graph, as well as the imported pages from file-based graph, i.e. the file-to-DB migration should retain the namespace hierarchy.

### Browser, Desktop or Mobile Platform Information

Logseq DB version at https://test.logseq.com

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by kerim** [comment]
I specifically need this in imported properties. For instance, I have contacts with page tags that list their organization:

FirstName LastName
tags:: contact, university/department

In the above example I need "university/department" to be imported as a namespace, and (in a related issue somewhere on here) I need it to link to all the other contacts with that tag.

**Comment by logseq-cldwalker** [comment]
@LER0ever Hi. I've added import support for namespaces. Can you verify that it works for you?

**Comment by kerim** [comment]
Namespaces seem to import properly for me. Thanks.

**Comment by LER0ever** [comment]
Hi @logseq-cldwalker, thanks for the quick fix! I can confirm that the namespaces are now correctly imported with file-to-DB migration. The parent property shows up as expected for me:

<img width="456" alt="image" src="https://github.com/user-attachments/assets/df71ea8e-aa22-4502-aff5-2f2ac61ac07e">

One small problem, not sure if it's a known bug, is that **namespace pages with alias** cannot be opened from the Cmd-K search menu, while normal pages can open just fine. Neither hitting enter nor mouse left clicking can open those namespace pages, should I create a new issue for that?

<img width="977" alt="image" src="https://github.com/user-attachments/assets/414f820b-8ee7-4c2b-b8e7-dac1485aae12">

**Comment by logseq-cldwalker** [comment]
Glad to hear it's working for both of y'all 🎉
@LER0ever New issue would be great. Worth sharing how to reproduce it e.g. creating alias in app or imported
