### ISSUE TITLE
Below (of) the block - English error

### ISSUE THREAD

**Issue by kerim** [logseq/db-test#139]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

In the text for the property UI position the last item says "Below of the block" when it should say "Below the block"

### Reproduce the Bug

No action necessary

### Expected Behavior

see above

### Screenshots

![Screenshot 2024-10-12 at 3 19 20 PM](https://github.com/user-attachments/assets/73236e32-7705-4897-a95e-20d2c9f8a1dd)

### Browser, Desktop or Mobile Platform Information

MacOS Brave Browser
2e5dfa3

### Additional Context

n/a

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
Thank you for the suggestion! The website should be updated soon.
