### ISSUE TITLE
[[Foo]] points to Foo page or Foo tag according to what was created first

### ISSUE THREAD

**Issue by alxlg** [logseq/db-test#14]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

There are two different behaviors depending on which one (`[[Foo]]` or `#Foo`) is created first.

- If you create `[[Foo]]` and then `#Foo` all the `[[Foo]]`, even future ones, points to the page `Foo`.

- If you create `#Foo` before any `[[Foo]]` is created, all the future `[[Foo]]` will point to the tag `#Foo`

### Reproduce the Bug

Reference a new page with `[[Foo]]`, then a new tag with the same name: `#Foo`.

Check that `[[Foo]]` (old and new ones) all point to the same Foo page. Instead `#Foo` just points to the tag Foo.

Now reference a new tag with `#Bar` and then reference for the first time the page `[[Bar]]`.

Check that this time `[[Bar]]` will point to the tag Bar and apparently there is no way to create the page [[Bar]] and reference it.

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
Close this in favor of #6.
