### ISSUE TITLE
block references not rendering on first load

### ISSUE THREAD

**Issue by blogbourri** [logseq/db-test#140]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

i frequently encounter block-node references that don't render

### Reproduce the Bug

1. make a block
2. in another block, make a reference to the block, then add a tag or page link
3. go to the tag or page link. the reference will render.
4. shift+reload the page. the reference will not render.
5. navigate to the source page for the block-node, and now the reference will render correctly again.

https://github.com/user-attachments/assets/9e27d7df-c5e4-4b87-896e-fcfe7fb9e450

### Expected Behavior

node references should always render correctly without navigating to their source, since their purpose is to link the currently viewed content to another context.

### Browser, Desktop or Mobile Platform Information

Current Revision: [f5bc9c6](https://github.com/logseq/logseq/commit/f5bc9c6)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
Thank you for reporting! The bug should be fixed, you can try it in 10 minutes.
