### ISSUE TITLE
Tags missing on tagged node table

### ISSUE THREAD

**Issue by hdansou** [logseq/db-test#146]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Sometime last week, a node tags are no longer available on a tag table, under a column named "tags

### Reproduce the Bug

Create a tag #book
create a node and tag it as a #book
Click on the #book tag to open it.
On the table, there should be a column Tags with the value of the node's tag.
This stopped work during the week

### Expected Behavior

All node tags should be available, allowing to filter by tag when more than one tag is assigned to a node.

### Screenshots

![image](https://github.com/user-attachments/assets/7d682d41-9ab8-478c-b1cd-82e5d60e0c1d)
 Comparing current and a commit from a week ago.

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by logseq-cldwalker** [comment]
Hi. Previous behavior was that the tags column always showed up on a tag table which was usually redundant. Agree that for a node with multiple tags the tags column would be helpful. Should be up on test.logseq.com in ~10m

**Comment by hdansou** [comment]
@logseq-cldwalker that works great. Thank you

**Comment by hdansou** [comment]
Related thread. for reference: https://github.com/logseq/db-test/issues/146
