### ISSUE TITLE
Cmd-j does not work if page/tage props aren't expanded

### ISSUE THREAD

**Issue by Bad3r** [logseq/db-test#147]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Cmd-j should expand page/tag/block properties to allow for quick editing. 

### Reproduce the Bug

1. hide page tags
2. Cmd-j

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
It should be fixed now.
