### ISSUE TITLE
Date Picker Navigation

### ISSUE THREAD

**Issue by kerim** [logseq/db-test#15]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

 I am trying to enter a birthday and I can only scroll back and forth one month at a time. For a 50 year old contact I'd have to click on the left arrow 600 times! Nor is there any way to manually edit the date in a date property without using the pop-up date selector (as there was in the MD version).

### Reproduce the Bug

Set a property which is a date.

### Expected Behavior

Clicking on the month should bring up a list of months, with a year on the top. Clicking on that should bring up a year navigation. This is a common date picker design in many other web apps now.

### Screenshots

![Screenshot 2024-08-14 at 3 22 55 PM](https://github.com/user-attachments/assets/bd28ba0e-e760-4391-9d14-979387d6c49a)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
Fixed on test.logseq.com.
![CleanShot 2024-08-30 at 08 03 53@2x](https://github.com/user-attachments/assets/9f4d2d93-6e14-4358-af04-60c951720957)
