### ISSUE TITLE
select all and copy inside codeblock copies blockID instead of content

### ISSUE THREAD

**Issue by Bad3r** [logseq/db-test#156]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

when pressing CTRL+A followed by CTRL+c inside a codeblock it will copy the block reference instead of the block content

### Reproduce the Bug

1. create a codeblock with example content
2. press CTRL+A followed by CTRL+c
3. paste somewhere else

### Expected Behavior

Copy block content 

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
Thanks for the report! It should be fixed now.
