### ISSUE TITLE
Copy block ref does not work

### ISSUE THREAD

**Issue by artemith** [logseq/db-test#157]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Copy block ref does not work. It did not display the refered blocks.

### Reproduce the Bug

1. Creat a block
2. Right click the block, select the "copy block ref"
3. Paste on a new block

### Screenshots

![image](https://github.com/user-attachments/assets/b8387e5c-eafb-4622-83ec-bc61a617c33e)
![image](https://github.com/user-attachments/assets/92d66868-7f8c-4710-8221-ae76909bf702)
![image](https://github.com/user-attachments/assets/38fbfbec-e11f-4b37-80c9-663f6bccb984)

### Browser, Desktop or Mobile Platform Information

Windows 10
Logseq DB: test.logseq.com

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
This bug has been fixed, you can give it a try in 10 minutes.

**Comment by artemith** [comment]
> This bug has been fixed, you can give it a try in 10 minutes.

It works, thank you!
