### ISSUE TITLE
Can not change URL type property value

### ISSUE THREAD

**Issue by artemith** [logseq/db-test#159]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Can not change URL type property value

https://github.com/user-attachments/assets/f5d7aa99-8592-4a57-847f-f5ef44174959

### Reproduce the Bug

1. Create a property in a node page
2. Select URL type
3. Try to change the property

### Browser, Desktop or Mobile Platform Information

Windows 10
test.logseq.com

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
@artemith Thank you for the report! It should be fixed now. To make it work, you need to remove and add the URL property again from the "test" page.

**Comment by artemith** [comment]
> @artemith Thank you for the report! It should be fixed now. To make it work, you need to remove and add the URL property again from the "test" page.

Thanks! It works.
