### ISSUE TITLE
when opening the settings, "Language" is selected

### ISSUE THREAD

**Issue by blogbourri** [logseq/db-test#16]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

when opening the settings, the Language setting is selected by default, making it easy to accidentally change the language. this is unlikely to be a common occurrence, but seems unintended. i discovered this by accident and was confused why everything was suddenly in french (though i imagine this would be a rare occurrence under normal usage for anyone).

### Reproduce the Bug

1. from journal, keyboard shortcuts `t s f`
2. your logseq is in french

### Expected Behavior

in the markdown version, `t s f` opens the settings (`t s`), but the Language setting is not default selected so further key presses do not change the language of the program.

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by xyhp915** [comment]
fixed in https://github.com/logseq/logseq/commit/f1cedc33ebe6642ad0ce957380f73e7012171db6
