### ISSUE TITLE
The preview window disapears when changing url type property value

### ISSUE THREAD

**Issue by artemith** [logseq/db-test#162]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

The preview window disapears when changing url type property value

### Reproduce the Bug

1. Create a page with a url type property
2. Try to change the empty property value in preview window

### Screenshots

https://github.com/user-attachments/assets/7379bb23-bd51-4ba1-aec0-131b089c0a63

### Browser, Desktop or Mobile Platform Information

windows 10
test.logseq.com

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
@artemith Can you check whether it's fixed? Thanks!

**Comment by artemith** [comment]
> @artemith Can you check whether it's fixed? Thanks!

Thanks! It works.
