### ISSUE TITLE
Unable to add a comment using # in codeblocks

### ISSUE THREAD

**Issue by Bad3r** [logseq/db-test#168]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Related to  #128 fix. 
Adding a comment via the syntax:
```
# comment
```
Removes the leading char `#` and turns the comment into code.

### Reproduce the Bug

1. create a /codeblock
2. add a comment `# comment`
3. exit codeblock edit mode i.e click on another block
4. Note that the `#` char is removed automatically

### Additional Context

@logseq-cldwalker pinging because I think you implemented the fix for #128 which is related. 

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
Thanks for the report, it should be fixed now.
