### ISSUE TITLE
Linking a header in text breaks formatting

### ISSUE THREAD

**Issue by Bad3r** [logseq/db-test#170]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

![image](https://github.com/user-attachments/assets/5f634117-6203-49e3-9f25-3926006cfa0c)

### Reproduce the Bug

1. create a header e.g `# Header`
2. in a block containing text link the header in the middle of it (block embed) [[header]]
3. it will be replaced by the block ID
4. Exit edit mode and note the formatting of the block. Linking the header added a new line before and after the block link

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by logseq-cldwalker** [comment]
Closing as this should be fixed and haven't heard back

**Comment by Bad3r** [comment]
> Closing as this should be fixed and haven't heard back


Sorry for the delay. I can confirm it's working as expected. 

Thank you!
