### ISSUE TITLE
Blocks with custom tags made inside of a page having the same tag does not show in the query search result.

### ISSUE THREAD

**Issue by niko-novice** [logseq/db-test#171]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

	- What is the bug?
		- Blocks with custom tags made inside of a page having the same tag does not show in the query search result.
		- eg create a page with tag `#health`. Then create a block inside that page with a `#health` tag. Then that block will not be shown in `#health` tag query. It will however be visible in the `#health` page.
	- How to recreate?
		- Do Following steps
			- Create a page `Exercise` with a tag `#health`.
			- Inside the page `Exercise`, create a block named `biceps` and tag it with tag `#health`.
			- Query search in today's journal page and select `health` from `tags` option.
		- Expected Result of query
			- I should see 2 searches in the query list titled `Exercise` and `biceps`.
		- What I actually see
			- I only see `Exercise` in the query list.

### Reproduce the Bug

- Do Following steps
	- Create a page `Exercise` with a tag `#health`.
	- Inside the page `Exercise`, create a block named `biceps` and tag it with tag `#health`.
	- Query search in today's journal page and select `health` from `tags` option.

### Expected Behavior

- Expected Result of query
	- I should see 2 searches in the query list titled `Exercise` and `biceps`.
- What I actually see
	- I only see `Exercise` in the query list.

### Screenshots

https://github.com/user-attachments/assets/b7f9c17c-8349-46dd-8218-bba77382cc91

### Browser, Desktop or Mobile Platform Information

Windows 11. Web Application.

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by logseq-cldwalker** [comment]
@niko-novice Hi. A fix for this should be on test.logseq.com in ~10 min

**Comment by niko-novice** [comment]
> @niko-novice Hi. A fix for this should be on test.logseq.com in ~10 min

Yes. The issue is solved !!!! Thank you !!!
