### ISSUE TITLE
URL Property type — Link is not clickable

### ISSUE THREAD

**Issue by Bad3r** [logseq/db-test#172]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Links are not clickable when added to a property of type `URL`

### Reproduce the Bug

1. create a property e.g. `website`
2. Set its type to a URL
3. add a link as value e.g. `https://logseq.com`
4. click on the link
5. Note that the link does not open
6. Compare to having a link in a regular block

> [!NOTE]
> Links in text type properties do not open as well. The issue seems to affect properties specifically. 
> Reproduce:
> create a text-type property and replicate the steps above.

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by logseq-cldwalker** [comment]
@Bad3r Hi. This is up on test.logseq.com to be reviewed

**Comment by logseq-cldwalker** [comment]
Closing as this should be fixed and haven't heard back

**Comment by Bad3r** [comment]
> Closing as this should be fixed and haven't heard back

Sorry for the delay. I can confirm its working as expected. 

Thank you!
