### ISSUE TITLE
journal: adding the "Code" Tag to a journal header cannot be undone

### ISSUE THREAD

**Issue by mschiff** [logseq/db-test#175]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Via "Set node property" you can add the #Code Tag to the heading which will render the headline as code. But removing the code tag will not undo that and there seems no way to get back to the original state

### Reproduce the Bug

1. Go to current journal page
2. Select "Set node property" on the headline
3. Choose "Tags"
4. Add the Code Tag
5. Try to undo that action

### Expected Behavior

I would expect the formatting be the original after removing the "Code" Tag from node properties

### Browser, Desktop or Mobile Platform Information

Firefox on test.logseq.com

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by logseq-cldwalker** [comment]
@mschiff Hi. Thanks for reporting this. This bug affects any node tagged with Math, Quote or Code as we were unable to undo any of those tags. I've pushed up a fix on test.logseq.com which will be available in ~10 min.

**Comment by mschiff** [comment]
Works as expected now, thanks for that super fast response and the fix and the great work you are doing here in general ;-)
