### ISSUE TITLE
Its not possible to link a block via ID & a page in the same block

### ISSUE THREAD

**Issue by Bad3r** [logseq/db-test#178]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When linking a block via its UUID in a block and linking a page via title e.g. [[page]]. The [[page]] link will disappear once you exit edit mode.

Example:
```edn
`[[674c10d0-7b45-4f73-9571-259c3ecfd109]] [[test]]`
```

### Reproduce the Bug

1. Create a text block
2. Create a page link
3. In a new block link the text block via ID and link the page e.g. `[[674c10d0-7b45-4f73-9571-259c3ecfd109]] [[test]]`
4. Exit block edit mode. Notice that the page link `[[test]]` will disappear

The same issue affects in-line tags. i.e. pressing shift + enter when adding a tag. 

### Additional Context

Issue does not affect tags 

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
Thank you for the report, this bug should be fixed now.
