### ISSUE TITLE
Advanced Queries don't work in Logseq db

### ISSUE THREAD

**Issue by niko-novice** [logseq/db-test#179]
Advanced queries not working in logseq db at test.logseq.com

Are they not enabled yet?

**Comment by logseq-cldwalker** [comment]
Hi. See https://github.com/logseq/docs/blob/feat/db/db-version.md#queries for how to start an advanced query. In general questions about the db version should be asked in discord. Bugs here should have the bug template filled out

**Comment by niko-novice** [comment]
> Hi. See https://github.com/logseq/docs/blob/feat/db/db-version.md#queries for how to start an advanced query. In general questions about the db version should be asked in discord. Bugs here should have the bug template filled out

I know how to start them. Its just that they don't work. 

When I type the advanced queries in the block code, it doesn't query anything.

It's that either the query format has changed or the keywords have changed and none of it is documented anywhere.
