### ISSUE TITLE
Some PDFs display incorrectly

### ISSUE THREAD

**Issue by artemith** [logseq/db-test#180]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Some PDFs display incorrectly in Logseq DB

### Reproduce the Bug

1. Import the uploaded PDF
2. Open the PDF

### Screenshots

![image](https://github.com/user-attachments/assets/4a40122e-fc2b-4034-9711-c08763265861)

### Browser, Desktop or Mobile Platform Information

test.logseq.com
Windows 10

### Additional Context

[梁燚焱 和 朱小能 - 2022 - 经济不确定性对企业信贷需求的影响研究.pdf](https://github.com/user-attachments/files/17985072/-.2022.-.pdf)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by logseq-cldwalker** [comment]
Hi. Can confirm this bug on Chrome. Interestingly this bug doesn't occur on desktop

@xyhp915 This could be an interesting bug to look into that only affects the browser pdf viewer

**Comment by logseq-cldwalker** [comment]
@xyhp915 Thanks for fixing. @artemith This is up on test.logseq.com to be reviewed

**Comment by artemith** [comment]
> @xyhp915 Thanks for fixing. @artemith This is up on test.logseq.com to be reviewed

It works! Thank you!
