### ISSUE TITLE
HTTP API Server stopped working after recent package upgrades

### ISSUE THREAD

**Issue by hdansou** [logseq/db-test#181]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

The HTTP API server stopped working after recent bump of dependencies.
Upon starting the APP, it returns the error message:

```
[Server] {:code "FST_ERR_PLUGIN_VERSION_MISMATCH", :name "FastifyError", :statusCode 500, :message "fastify-plugin: @fastify/cors - expected '4.x' fastify version, '5.1.0' is installed"}
```

### Reproduce the Bug

Enable the HTTP API Server under Settings >> Features
Restart the App

### Expected Behavior

HTTP API server should start without error

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by logseq-cldwalker** [comment]
@hdansou Hi. A fix has been pushed

**Comment by hdansou** [comment]
Thank you. It is working.
