### ISSUE TITLE
string-width missing from /static/yarn.lock

### ISSUE THREAD

**Issue by Bad3r** [logseq/db-test#182]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Hello,
After the recent package was updated an error popped up during the electron-forge process:
```
$ /home/chell/git/logseq/static/node_modules/.bin/electron-forge package
✔ Checking your system
✔ Preparing to package application
✔ Running packaging hooks
  ✔ Running generateAssets hook
  ✔ Running prePackage hook
❯ Packaging application
  ❯ Packaging for x64 on linux
    ✖ Copying files
      › Failed to locate module "string-width" fr…
        This normally means that either you have …
    ◼ Preparing native dependencies
    ◼ Finalizing package
◼ Running postPackage hook

An unhandled rejection has occurred inside Forge:
Error: Failed to locate module "string-width" from "/home/chell/git/logseq/static/node_modules/@isaacs/cliui"
```

The issue is simply solved by 'cleaning'/removing static/yarn.lock and running yarn install again. This will update electron-forge from 7.3.1 to 7.6.0 and update its deps to make it compatible with the new updates.

There might be another way to solve this as it seems like the root of the issue is that the package `string-width` is not available 

```
❯ yarn list string-width
yarn list v1.22.22
warning Resolution field "node-gyp@10.0.1" is incompatible with requested version "node-gyp@^9.0.0"
warning Filtering by arguments is deprecated. Please use the pattern option instead.
Done in 0.48s.
```

CC @xyhp915

### Reproduce the Bug

1. build logseq desktop app (might be a Linux only issue)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by logseq-cldwalker** [comment]
> The issue is simply solved by 'cleaning'/removing static/yarn.lock and running yarn install again

Hi. Interesting. I'm on osx, using node 20.18.1 and yarn 1.22.22 and I'm able to install from the current static/yarn.lock. Fwiw after https://github.com/logseq/logseq/pull/11620 I was unable to start electron locally from a clean static/, until I added https://github.com/logseq/logseq/commit/c6bf04c2877ec85105b82a791aae63819e60f62e. Any contributions are welcome to linux as long as they install fine on osx

**Comment by Bad3r** [comment]
> Hi. Interesting. I'm on osx, using node 20.18.1 and yarn 1.22.22 and I'm able to install from the current static/yarn.lock e.g. `cd static && rm -rf node_modules && yarn install; cd -`. 

The issue I am having only happens when electron-forge runs. I think it only runs when you are trying to build the desktop application i.e `yarn release-app`

**Comment by Bad3r** [comment]
This issue seems to have been fixed. Thank you!
