### ISSUE TITLE
Can not write in Journal - Input loses focus on click

### ISSUE THREAD

**Issue by aplumez** [logseq/db-test#183]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Hi,

I was just invited to test it, so I followed the instructions exactly as they gave us:
"To start using Logseq DB, head over to https://test.logseq.com/. In the top left sidebar, click Demo and then Create db graph. Enter a graph name and hit Submit."

I was then in the context of my new graph called "testing-db", in the "Journals" section. At this point, I was able to write text because the focus was directly on the first block <textarea>. Then, I clicked outside the input (lost focus), and I was no longer able to give the focus back to the <textarea>.

I then tried the exact same thing using Chromium, and it worked like a charm.

### Reproduce the Bug

1. Create a new db graph
2. Without clicking anywhere, just write "Anything" (it works)
3. Click outside the block (i.e. on the Journal title)
4. Try to append text in the "Anything" block (it does not work, the textarea cannot be focused)

### Expected Behavior

When I click on a block textarea, it should take the focus and I should be able to edit the text.

### Screenshots

https://github.com/user-attachments/assets/2509acae-b9e6-4fbd-88a4-20872ae37b76

### Browser, Desktop or Mobile Platform Information

OS: Fedora Workstation 41
Browser: Firefox 133.0 (64bits)
LogSeq version: 0.10.10 (https://test.logseq.com)

### Additional Context

The only line that might be interesting in the JS Console is:
[frontend.modules.shortcut.data-helper] {:shortcut/binding-not-found {:id :ui/highlight-recent-blocks}, :line 82}

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by zetashift** [comment]
It seems that the only way to get focus in the text back again it to press enter on the node, after you've clicked on a node.

**Comment by tiensonqin** [comment]
Thank you for the report! I just pushed a fix, please try it and let me know whether it works after 10 minutes, the website is building now.

**Comment by aplumez** [comment]
I confirm it has been resolved! Thank you for the fix! :+1:
