### ISSUE TITLE
Two blocks cannot be referenced in the same line in Logseq DB.

### ISSUE THREAD

**Issue by JHOAbi** [logseq/db-test#184]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When I try to reference two different already existing blocks in one line, the second reference gets deleted, although in can first be selected via typing "[[" and selecting the block.

### Reproduce the Bug

1. create a new node.
2. type [[
3. Choose an already existing Block on another page and hit enter.
4. The block reference shows up.
5. type "and " in the same line
6. type [[ again
7. Choose another block to reference
8. hit enter.
9. the selected block does not show up.

### Expected Behavior

The first und the second referenced blocks show up and can be clicked on as in Logseq MD.

### Screenshots

Pleas find the console log in the attachment.
[test.logseq.com-1733581786834.log](https://github.com/user-attachments/files/18048785/test.logseq.com-1733581786834.log)

### Browser, Desktop or Mobile Platform Information

macOS Sequoia, Chrome browser, logseq DB

### Additional Context

It works without problems s expected in Logseq MD, when selecting the blocks via typing of ((... 

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
Thank you for the report, this bug should be fixed now.
