### ISSUE TITLE
Youtube player width auto

### ISSUE THREAD

**Issue by hdansou** [logseq/db-test#188]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Since https://github.com/logseq/logseq/commit/4477dcfb95eefe7f47895720eec6f2ae2ceca501 the youtube player width is not automatically resizing

### Reproduce the Bug

1. Add a new video {{video https://www.youtube.com/watch?v=aim5x73crbM}}
2. Do t + w for wide mode
3. The video size remains the same

### Expected Behavior

The size of the video should be responsive, and scale based on the width of the content size or screen.

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by cannibalox** [comment]
related to #110 

I think this would fix the issue
```
.aspect-video {
    aspect-ratio: 16/9;
    width: 100%;
    height: auto;
}
```

**Comment by tiensonqin** [comment]
I don't like the video player to take up a lot of space, but I'm OK with that because I can change it in custom.css, and we might support iframe resizing in the future.
So, I will update it to what @cannibalox suggested; thank you both!
