### ISSUE TITLE
Error importing a File Graph: A duplicate journal page is created when the page contains a task

### ISSUE THREAD

**Issue by geosmina** [logseq/db-test#192]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When I try to import a File Graph, all the Journal pages that have a task in them end up duplicated. The new pages created are blank and only have the Linked Reference to that same date.

1. The page with tasks:
![Task in a Journal](https://github.com/user-attachments/assets/e24425a0-d3ab-49d5-a167-bc9b43a4c8a8)

2. The blank page with the linked reference: 
![Duplicated Journal Entry](https://github.com/user-attachments/assets/78cb2d1c-6ef1-4594-8fef-afcfb2de39bf)

### Reproduce the Bug

1. Go to "Import existing notes".
2. Select "File to DB Graph".
3. Select the File Graph folder.
4. Import
5. Search for a journal page that has a task in it. There should be two pages with that date.

### Browser, Desktop or Mobile Platform Information

Logseq DB 0.10.10 - 7c2d17e
Firefox 133.0 (64-bit)
Google Chrome 131.0.6778.108 (64-bit)

### Additional Context

- This behavior is independent of the status of tasks.
- This appears to only occur in journals where the tasks have a deadline.

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by geosmina** [comment]
Files sent by email for privacy reasons. If you need more, please let me know.

**Comment by logseq-cldwalker** [comment]
Obrigado. A fix should be up on test.logseq.com in ~10m

**Comment by geosmina** [comment]
Worked as a charm!

**Comment by logseq-cldwalker** [comment]
Glad it works and yes issues can be closed when they're fixed
