### ISSUE TITLE
Can not scroll PDF with PageUp/PageDown button

### ISSUE THREAD

**Issue by artemith** [logseq/db-test#194]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Can not scroll PDF with PageUp/PageDown button

### Reproduce the Bug

1. Import a PDF into Logsesq DB.
2. Click the PDF to open it.
3. Press PageUp or PageDown

### Expected Behavior

The PDF page should scroll up/down.

### Browser, Desktop or Mobile Platform Information

Windows 10
test.logseq.com
Microsoft Edge

### Additional Context

![image](https://github.com/user-attachments/assets/a476a078-cbda-4509-8504-d1db12a42296)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by xyhp915** [comment]
Good suggestion! Currently, you can achieve this function by customizing shortcut keys.
![CleanShot 2024-12-23 at 12 21 19@2x](https://github.com/user-attachments/assets/90513d0b-c45f-42b6-8657-d258ac259c40)

**Comment by artemith** [comment]
Thanks!
