### ISSUE TITLE
Page and Tag with same name defaults to using Page instead of Tag

### ISSUE THREAD

**Issue by Siferiax** [logseq/db-test#2]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When both a page and a tag exists with the same name, writing `#name` results in it getting changed to `[[name]]` instead of adding the tag to the line.

### Reproduce the Bug

1. Create a page with the name `test`
2. Create a tag with the name `test`
3. Write a line in the journal: `Adding the tag #test`
4. The line gets changed to `Adding the tag [[test]]`

### Expected Behavior

When using `#test` it should add `test` as a tag.
When using `[[test]]` it should add `test` as a page link.

### Browser, Desktop or Mobile Platform Information

Brave browser
DB version of Logseq at https://test.logseq.com/

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by logseqramses** [comment]
I can reproduce the issue. The Tag only appears when you hit `Enter`; if you type the tag name all out and click out of the block it will instead turn into a `[[page reference]]`:

https://github.com/user-attachments/assets/51303853-9666-4e21-ab27-0a2660eccdcf

**Comment by Siferiax** [comment]
https://github.com/user-attachments/assets/08dcaa21-7f32-4aaa-8e78-e7ffaf11f2d9

Actually I see the same behavior regardless of input type.

**Comment by tiensonqin** [comment]
Thanks for the report, I can reproduce the bug.
I'll push a fix soon.

**Comment by tiensonqin** [comment]
@Siferiax @logseqramses I just pushed a fix, let me know whether it works for you.

**Comment by logseqramses** [comment]
@tiensonqin There's no difference for me. If I don't hit `Enter`, the tag is still turned into a page reference:

https://github.com/user-attachments/assets/ba64050f-2de1-4cff-935d-3e0321cc9ef5

**Comment by tiensonqin** [comment]
@logseqramses That's expected behavior for now. But this is gonna be changed if we decide to bring inline tags back. I'll close this issue.

**Comment by logseqramses** [comment]
@tiensonqin :
> That's the expected behavior for now.

So we still have two behaviors for the same syntax? Based on whether you hit enter or you click out of the block, it has one behavior (turn syntax into a Tag) or another (turn syntax into a page reference)?

That is very confusing, especially as there is no hint in the UI that this behavior exist. If we do not make this consistent to one behavior, I predict we will get many more bug reports like this.

**Comment by Siferiax** [comment]
Can at least confirm that pressing enter now actually adds the tag instead of the page reference.
