### ISSUE TITLE
block reference reverts to uuid after destination block is edited under certain conditions

### ISSUE THREAD

**Issue by blogbourri** [logseq/db-test#21]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

the newer style text-based block references revert to the older uuid style references after a particular sequence of edits.

### Reproduce the Bug

1. make a block with text in it, block a (text should not match any pre-existing nodes)
2.  add any tag to the block
3. in a new block, create a block reference to block a
4. return to block a, select the text, type [[ and create a new page out of the text
5. the block reference created previously switches to uuid style reference

### Expected Behavior

i hadn't encountered uuid references in the db version previously, so i believe the intended result is that the text of the reference just update to reference text

### Screenshots

<img width="832" alt="Screenshot 2024-08-16 at 10 27 04 AM" src="https://github.com/user-attachments/assets/f2a917a9-a88f-4a77-8f04-bcbbdf0069d9">

### Additional Context

no errors in console

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
Fixed.
