### ISSUE TITLE
CSS - Property Key performs line-break on words instead of normal

### ISSUE THREAD

**Issue by Zyrohex** [logseq/db-test#23]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Created a block with a property called "Requirements" and noticed that the CSS stylesheet is performing line-break within the word itself, where I think it should only do line-break on whitespace instead. Improves readability of the property key.

### Reproduce the Bug

1. Open left sidebar
3. Open right sidebar
4. Navigate to your today's journal page
5. Create block with property key called "Requirements" or anything else that's a single word and has around 8+ chars
6. Set the block status to DOING so it appears in the journal's query
7. Open the block in the right sidebar
8. If the property key has not performed word-break yet, zoom in until it does.. and make note of the behavior how it performs word-break within the word itself instead of whitespace.

### Expected Behavior

Property key's should only line break on whitespace rather than the word itself

### Screenshots

![image](https://github.com/user-attachments/assets/1cb42174-a613-47e9-8f7e-c89ec7b71b5d)

### Browser, Desktop or Mobile Platform Information

Logseq DB Test Environment
Commit = https://github.com/logseq/logseq/commit/6032a1d

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by xyhp915** [comment]
fixed in https://github.com/logseq/logseq/commit/aa0b0799e5bd814d454aa521421c341eb4f482a8

**Comment by Zyrohex** [comment]
Resolved - closing ticket. Thanks @xyhp915!
