### ISSUE TITLE
Putting the text "#Task" in a block breaks creating new tasks

### ISSUE THREAD

**Issue by phoenixeliot** [logseq/db-test#24]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

I was adding tasks to my daily page (my first page ever). I added a note about "#Task" auto-hiding being odd. Then, after that, I could no longer create tasks via any means (cmd-enter or /task), even after refreshing the page — and refreshing the page deleted everything in my graph (in that one daily file I had).

Upon later testing, refreshing didn't delete the contents of the page, so I'm not sure what's up with that happening the first time I tried this.

### Reproduce the Bug

1. Create a new graph
2. Type in a block on the daily page
3. Type "#Task stuff" (without quotes). 
4. Press escape to prevent "#Task" from being removed/converted to a tag on the right, leaving the block just saying "#Task stuff".
5. Press Enter to create a new block

6a. Press cmd-enter to try to create a task.

6b. Type /todo and press enter to select the slash command item

Outcome: No task bubble or #Task tag is added to the block. Refreshing does not fix this.
However, if you press cmd-z before reloading, that removes the entire block with "#Task stuff" in it, and that fixes adding new tasks in other blocks.

### Expected Behavior

Using either method 6a or 6b, a new TODO task should be created after pressing cmd-enter, and the #Task tag should be added to the block.

### Screenshots

Here is a video of me typing various things and trying to change statuses using cmd-enter. At the end, I undo some of it, and then redo until the redo stack stops redoing things — a LOT of erroneous entries get added to the redo stack in the process of all this, somehow.

https://github.com/user-attachments/assets/eb4ba7fd-d39c-4773-8cc5-abf7834dc7e1

Here is a simpler video with more undo/redos happening (in 2 parts; one undoing all the way back, one undoing only partly back); how far I undo seems to affect whether the breakage happens

https://github.com/user-attachments/assets/89a47e9d-1ef2-42ef-96c8-7e69e51cf1c2

### Browser, Desktop or Mobile Platform Information

macOS 14.4.1
Brave browser Version 1.68.137
Using https://test.logseq.com which says version 0.10.10 (6032a1d)

### Additional Context

The undo/redo stack also seems to get really broken if you press cmd-enter while on a block after the "#Task stuff" block, and then redo it; the redo causes the task to be created on the "#Task stuff" block instead of the one you pressed cmd-enter on.

It seems that when undone, some actions are not being removed from the undo stack at all, when this bug is happening.

### Error logs

The following error is generated when I run `/todo` or press cmd-enter: "Nothing found for entity id :logseq.class/Task"
![Screenshot 2024-08-19 at 15 31 51](https://github.com/user-attachments/assets/10f065a4-5540-400e-b0cb-bb56ddf04cbf)

Going by the error in the console, I think having "#Task" in a block replaces or deletes some internal entity and breaks the code for adding the old kind of entity.
Which I think means it permanently breaks the graph's task entity :)) 

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by phoenixeliot** [comment]
Additionally while in this broken state on mobile, if I have 4 blocks like this:
```
- assume this one is a todo block
- #Task stuff
- /task
- 
```
Then if my cursor is on the last, blank block, I cannot press backspace to move back to the previous block.

**Comment by phoenixeliot** [comment]
I'm not sure how I caused this video's behavior to happen, and am having trouble reproducing it, but I think it was on a graph that had been corrupted by this bug. Pressing Enter after blocks with an unused invalid slash command was causing new lines to be entered into strange places, causing other lines to _rearrange relative to each other_, and the cursor to jump to _different_ strange places.

I don't know if the slash command text was actually relevant or not.

https://github.com/user-attachments/assets/8b0cd6aa-3fac-4f3c-b11e-633e2ff119e9

**Comment by phoenixeliot** [comment]
After dumping before/after DBs for minimal breaking changes, it only causes this change in the DB;

It replaces this:
```
1    [[]]
```
With this:
```
1    [[],[[62,"~:block/updated-at",1724097614029,-536870919],[62,"^0",1724097633792,536870919],[63,"^0",1724097614030,-536870919],[63,"^0",1724097633791,536870919],[63,"~:block/refs",54,536870919],[63,"~:block/tags",54,536870919],[54,"^0",1724097613868,-536870919],[54,"^0",1724097633790,536870919],[54,"~:block/created-at",1724097613868,-536870919],[54,"^3",1724097633790,536870919],[54,"~:db/ident","~:logseq.class/Task",-536870919],[54,"^4","~:user.class/Task",536870919],[63,"~:block/title","",-536870919],[63,"^7","#~^00000002-1282-1814-5700-000000000000",536870919]],[],[[63,"^1",54,-536870921],[63,"^1",54,536870921],[63,"^1",7,536870921]],[[63,"~:block/path-refs",62,-536870922],[63,"^8",62,536870922],[63,"^8",7,536870922],[63,"^8",54,536870922],[62,"~:block/tx-id",536870916,-536870922],[62,"^9",536870921,536870922],[63,"^9",536870916,-536870922],[63,"^9",536870921,536870922],[54,"^9",536870921,536870922]]]
```

**Comment by tiensonqin** [comment]
@phoenixeliot Thanks for the report, please try https://logseq-db-demo.pages.dev/#/ in 10m.

**Comment by tiensonqin** [comment]
Closing this now, I'll re-open it if anyone still encounter this bug.
