### ISSUE TITLE
I can undo creation of the journal page, and if I do, it breaks redo

### ISSUE THREAD

**Issue by phoenixeliot** [logseq/db-test#25]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

I undid so far back that it deleted the journal page, and then redo stopped working.
I think this may only apply when editing a newly created graph.

### Reproduce the Bug

1. Create a new graph
2. Type some blocks on the today page
3. Press Undo (cmd-z) until all the text is gone, then a couple more times after that
Result: The date for today's page is deleted

5. Press Redo (cmd-shift-z)
Result: The page title comes back

6. Press Redo again
Result: The stuff you typed *does not* come back

7. Press Redo as many more times as necessary to equal however many times you undid
Result: *all* the things you undid come back, all at once.

There's also a weird broken state in the middle there after step 6 if you try to click on the page and edit it.

### Expected Behavior

Undo/redo should work as expected. And I should not be able to undo the implicit creation of the today page by pressing cmd-z.

### Screenshots

2 cycles of full undo/redo, and then the broken intermediate state after undoing and only partially redoing (and then doing all this again some more times):

https://github.com/user-attachments/assets/940580b2-82d9-4f34-814d-752786ba8ec9

### Browser, Desktop or Mobile Platform Information

macOS 14.4.1
Brave browser Version 1.68.137
Using https://test.logseq.com which says version 0.10.10 (6032a1d)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
Fixed by https://github.com/logseq/logseq/commit/f1b0622ecd51485a674f7b8d3bcd8995b01fc4d0.
