### ISSUE TITLE
If I undo text, that text still shows up in search results

### ISSUE THREAD

**Issue by phoenixeliot** [logseq/db-test#26]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Typed some stuff, then undid it, then searched for it with cmd-k. I find that page in the search results.

Additionally, sometimes this also deletes what I just typed. Will file that as a separate bug.

### Reproduce the Bug

1. Type "foo" in a block on a journal page in a new graph
2. Undo the typing of "foo". Press enter to make sure that first block saves.
3. Press cmd-k to search; type "foo" in the search bar. The page you typed and undid the text in will still appear in the search results.

### Expected Behavior

The page should not appear in the search results if that page does not have that text anymore.

### Screenshots

https://github.com/user-attachments/assets/69b036df-a31c-4679-8c9c-49d079399b1f

### Browser, Desktop or Mobile Platform Information

macOS 14.4.1
Brave browser Version 1.68.137
Using https://test.logseq.com/ which says version 0.10.10 (6032a1d)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
Fixed by https://github.com/logseq/logseq/commit/009ba0b6542fb17c46d282c4b453e49be4b82df2.
