### ISSUE TITLE
If I open the cmd-k search bar quickly, it deletes whatever I just typed

### ISSUE THREAD

**Issue by phoenixeliot** [logseq/db-test#27]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

I typed some stuff, then pressed cmd-k quickly after. The stuff I just typed was deleted from me pressing cmd-k (just before the search modal opens)

### Reproduce the Bug

1. Type some text into a block
2. Immediately (probably within 500ms, if I remember the code right) press cmd-k to open the search modal
3. Close the search modal

Result: The stuff you typed is deleted.

### Expected Behavior

The stuff I type should never be deleted by anything except stuff specifically intended to do that.

### Screenshots

https://github.com/user-attachments/assets/b3d0f030-c1f1-43c7-be2d-7c36778a30ad

### Browser, Desktop or Mobile Platform Information

macOS 14.4.1
Brave browser Version 1.68.137
Using https://test.logseq.com/ which says version 0.10.10 (6032a1d)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
Fixed by https://github.com/logseq/logseq/commit/69816cdd2bf72d0920ce69aaf9563c8d686d8000.
