### ISSUE TITLE
Variables like "<%current page%>" do not work

### ISSUE THREAD

**Issue by Zyrohex** [logseq/db-test#28]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Trying to use a variable inside a query "<%current page%>" but it fails to work.

### Reproduce the Bug

1. Create a page
2. Open that page
3. Create a query and use the following query statement = `{{query <%current page%>}}`
4. Click outside the query so that it runs
5. Notice that the query statement only shows square brackets but does not display the name of the page

### Expected Behavior

`<%current page%>` should reference the current page

### Screenshots

![image](https://github.com/user-attachments/assets/9bca3f30-8bd0-481d-8735-b669b362ddfb)

### Browser, Desktop or Mobile Platform Information

Logseq DB Test Environment
Commit = https://github.com/logseq/logseq/commit/ae27032

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by logseq-cldwalker** [comment]
Hi. Confirmed. Pushed up a fix that should be available in ~10m on https://logseq-db-demo.pages.dev/

**Comment by logseq-cldwalker** [comment]
Closing. This is now up on https://test.logseq.com/. Feel free to comment if it's not fixed

**Comment by Zyrohex** [comment]
@logseq-cldwalker - confirmed this is resolved. Thanks!
