### ISSUE TITLE
DB: properties like background-color show up in search

### ISSUE THREAD

**Issue by Bad3r** [logseq/db-test#29]
### Search first

- [X] I searched and no similar issues were found

### What Happened?
in page search Mod+shift+k
![image](https://github.com/user-attachments/assets/fef78aaf-a473-4ce3-8061-0cae51228c4f)
Graph search Mod+k
![image](https://github.com/user-attachments/assets/94b9e70b-0f44-45dc-9bae-d6b19656264f)

### Reproduce the Bug

search for background in Mod+shift+k or Mod+k

**Comment by logseq-cldwalker** [comment]
Hi. I moved your db issues to this repo as we're tracking them here. We'll make an announcement when we want issues opened on the main repo

**Comment by Bad3r** [comment]
> Hi. I moved your db issues to this repo as we're tracking them here. We'll make an announcement when we want issues opened on the main repo

Thank you good to know. I'll start reporting new issues here.

**Comment by logseq-cldwalker** [comment]
Wrt to the issue, this is intentional behavior. If we didn't show public built-in properties in search, users wouldn't be able easily find and customize more powerful ones like status

**Comment by tiensonqin** [comment]
In the future, we can enhance the search filters to hide built-in properties or other nodes. 
I'll close this issue for now, you can add this to #alpha-db-feedback.
