### ISSUE TITLE
DB: Its not possible to edit a property from the property dialog

### ISSUE THREAD

**Issue by Bad3r** [logseq/db-test#30]
### What Happened?

When adding a new value for a property and then deciding to change it the option gets disabled:

video demo:

https://github.com/user-attachments/assets/25baba71-1aa2-4440-bccf-986053047402

I really don't like that the first option in the select menu is not 'create new alias' and it defaults to the most similar existing alias. It makes the workflow slower.

**Comment by logseq-cldwalker** [comment]
Hi. I wouldn't expect to be able to edit the property from this dialog as hovering over the property doesn't give an indication it's editable. Marking as enhancement unless @xyhp915 thinks we should close this as wontfix

**Comment by xyhp915** [comment]
Hi @Bad3r. This part of the UX is still being continuously optimized, and we will find out a more efficient and reasonable way to enhance the experience.

**Comment by tiensonqin** [comment]
Closing this issue now since it's able to edit a property and configure it in the property dialog.
