### ISSUE TITLE
DB: linking a [[block]] doesn't respect URL formatting

### ISSUE THREAD

**Issue by Bad3r** [logseq/db-test#31]
the steps to reproduce:
1. create a block with a link `[Logseq](https://logseq.com)`
2. Create a second block
3. Add a new property to the second block that allows using text as a value
4. in the text value of the property reference the first block with a link i.e `[[BLOCK ID]]`
5. exit edit mode, the link in the value will be displayed without formatting `[[[Logseq](https://logseq.com)]]`

The second method to reproduce based on @tiensonqin example:
1. create a block with a link `[Logseq](https://logseq.com)` tag the block with `#link`
2. in another block create a block reference to the link [[BLOCK ID]]
6. exit edit mode, the linked block will show the link as text without formatting i.e `[[[Logseq](https://logseq.com)]]`

![image](https://github.com/user-attachments/assets/d168ff81-7d81-4475-88d4-47abbe4bd4bb)

**Comment by logseq-cldwalker** [comment]
Hi. I can't reproduce this as step 2 needs more detail and the screenshot doesn't match the description. Here's what I'm seeing
<img width="758" alt="Screen Shot 2024-08-21 at 3 51 06 PM" src="https://github.com/user-attachments/assets/6b5f3516-1137-4aec-a42f-cfaa12b96958">

**Comment by tiensonqin** [comment]
I'm able to reproduce this bug by adding a #link tag.
![CleanShot 2024-08-23 at 16 15 33@2x](https://github.com/user-attachments/assets/43a888ab-a2dc-42a2-a36d-08712ed07d99)

**Comment by Bad3r** [comment]
> Hi. I can't reproduce this as step 2 needs more detail and the screenshot doesn't match the description. Here's what I'm seeing <img alt="Screen Shot 2024-08-21 at 3 51 06 PM" width="758" src="https://private-user-images.githubusercontent.com/97210743/360077734-6b5f3516-1137-4aec-a42f-cfaa12b96958.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1NzU3ODgsIm5iZiI6MTcyNDU3NTQ4OCwicGF0aCI6Ii85NzIxMDc0My8zNjAwNzc3MzQtNmI1ZjM1MTYtMTEzNy00YWVjLWE0MmYtY2ZhYTEyYjk2OTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDA4NDQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwODhjZjk5ZmRiN2ZmNTBlOTI3YjNkY2JiMTMwNzQyMWFlNzZjN2NmNjFiMDFjZTUxY2NkOTM5YzM2YzAwNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pAbGBABkBB9qXsnp4tTAvkWZgLmWFNIIVFtqQSAZKM4">

my bad here are the steps to reproduce:
1. create a block with a link `[Logseq](https://logseq.com)`
2. Create a second block
3. Add a new property to the second block that allows using text as value
4. in the text value of the property refrence the first block with a link i.e `[[[Logseq](https://logseq.com)]]`
5. exit edit mode, the link in the value will be displayed without formatting

Second method to reproduce based on @tiensonqin example:
1. create a block with a link `[Logseq](https://logseq.com)` tag the block with `#link`
2. in another block create a block reference to the link [[BLOCK ID]]
6. exit edit mode, the linked block will show the link as text without formatting i.e `[[[Logseq](https://logseq.com)]]`

Updated the OG issue with the steps. Sorry for the late response.

**Comment by tiensonqin** [comment]
This should be fixed now, it'll take 10m to update test.logseq.com.

**Comment by Bad3r** [comment]
> This should be fixed now, it'll take 10m to update test.logseq.com.

The issue is fixed. Thank you!
