### ISSUE TITLE
DB: Unable to set property text fields like description from popup window on a block property

### ISSUE THREAD

**Issue by Bad3r** [logseq/db-test#32]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

See video:

https://github.com/user-attachments/assets/0b3eef40-ae84-432b-bb07-ae64d902162c

### Reproduce the Bug

1. Add new block property
2. Set type to text
3. Attempt to set a value
4. Press enter

### Expected Behavior

Value to be saved on enter or by pressing a save button (not available).

Possibly related to logseq/db-test#30

**Comment by logseq-cldwalker** [comment]
Hi. Confirmed. This should be fixed and up on https://test.logseq.com/ in about ~10 min

**Comment by logseq-cldwalker** [comment]
Closing. Feel free to comment if it's not fixed
