### ISSUE TITLE
DB: linking a task block with a [[page]] returns an empty string

### ISSUE THREAD

**Issue by Bad3r** [logseq/db-test#33]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

linking a task ((block)) with a [[page]] returns an empty string

https://github.com/user-attachments/assets/c965082a-7d5f-405a-823a-f0de8f755faa

### Reproduce the Bug

1. create a task block with a page link
  - [] example task with a [[page]] link
2. link the previous block with [[block ID]]
3. exit edit mode; only empty brackets show up

**Comment by tiensonqin** [comment]
Fixed by https://github.com/logseq/logseq/commit/1b6cbeabecebbdb7f17bed5540b6be758f43db67.
