### ISSUE TITLE
DB: Linking a [[block]] with a header breaks line formatting

### ISSUE THREAD

**Issue by Bad3r** [logseq/db-test#34]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

![image](https://github.com/user-attachments/assets/2a19bfb2-3284-4dab-a025-b8ca7b985677)

Steps to reproduce:
1. create a block with a header any type H1,...,H5
2. In a second block add a test [[link to header block]] test
3. Exit edit mode; the block is now broken into 3 lines

Demo

https://github.com/user-attachments/assets/91ed0498-0a2c-4a00-ab24-875a4561bc53

**Comment by logseq-cldwalker** [comment]
Hi. I can reproduce. I agree displaying this inline is what I would expect. @xyhp915 Could you take a look at this when you get a chance?

**Comment by xyhp915** [comment]
fixed in https://github.com/logseq/logseq/commit/3241707534a088256a3841646412970862d94867

<img width="404" alt="CleanShot 2024-08-22 at 10 46 59@2x" src="https://github.com/user-attachments/assets/c48fb59d-d56c-4f53-b177-6cac02a135b6">
