### ISSUE TITLE
Removing a node-reference to a page deletes the page when the page only contains properties

### ISSUE THREAD

**Issue by Zyrohex** [logseq/db-test#35]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

While creating a new node page I noticed that after I removed the node reference from my journal, the actual page was deleted, even though I can still perform node references.. But clicking on those node references returns a blank screen.

### Reproduce the Bug

1. Open journal page
2. Add a new page node reference
3. Go into the page and add some content in properties
4. Navigate back to the journal page and now remove the node reference
5. Try searching for the page you created and notice it does not exist anymore

### Expected Behavior

Removing a node reference, regardless if the page contains either regular notes, or properties filled out, the page should not be deleted.

### Screenshots

https://github.com/user-attachments/assets/669668e2-276e-4eff-9809-c7757db97730

### Browser, Desktop or Mobile Platform Information

Logseq DB Test Environment

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
@Zyrohex test.logseq.com will be ready in 10m, please give it a try and let me know whether it works for you.

**Comment by Zyrohex** [comment]
@tiensonqin - this looks to be partially resolved. So it does not delete the page anymore which is great, however this or another commit has now caused page properties to remain hidden by default. If it's unrelated I can open a new issue:

https://github.com/user-attachments/assets/65cdb75e-7a84-435c-90c1-8179c6e58516

**Comment by Zyrohex** [comment]
More context - if you add a tag to the page then the properties will always display as i'd expect. However once I remove the tag the properties section goes back to a hidden state by default.

**Comment by Zyrohex** [comment]
This is resolved - thanks!
