### ISSUE TITLE
Setting a property text node to "multiple values" and adding a child node to one of those nodes creates a self reference to itself

### ISSUE THREAD

**Issue by Zyrohex** [logseq/db-test#36]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Basically when you have a property that's setup as a text schema and configured to use multiple values, after you add multiple values to that property, and then add a child node to any of the parent nodes, you'll notice all the parent nodes then suddenly show they have references tied to them.. When you click on the reference, its a reference to its ownself, so it ends up in a endless loop of trying to display its own block repeatedly until it likely crashes.

### Reproduce the Bug

1. Create a block
2. Add a property that is configured for a text schema to accept multiple values
3. Add multiple values to the property
4. Now add a child node to any of the parent blocks and notice the side of the blocks now all show they have references
5. Drill down to any of those blocks and make note how it ends up in an endless loop referencing itself

### Expected Behavior

Adding a child node should not be creating a self reference to any of these blocks. Also we should not have any instances where a block ends up references its ownself.

### Screenshots

https://github.com/user-attachments/assets/d19accc7-98db-409b-962d-964f4de9a7e4

### Browser, Desktop or Mobile Platform Information

Logseq DB Test Environment

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by Zyrohex** [comment]
Some more context on the issue. This appears to only occur when the node is a task. If the node is not a task, child nodes can be created no problem.

**Comment by logseq-cldwalker** [comment]
Hi. Interesting find. I was able to reproduce this by creating a :default property with many values, creating a block with that property and a task value and then creating a child block under the task. I was also able to repro with any custom class, not just a `Task`. Anyways pushed up to test.logseq.com and should be available to try in ~10m

**Comment by Zyrohex** [comment]
@logseq-cldwalker - tested and it looks like its resolved.
