### ISSUE TITLE
Trying to edit a new property crashes Logseq

### ISSUE THREAD

**Issue by bgrolleman** [logseq/db-test#38]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Error caught by UI! if I add a text property and try to modify it. 

### Reproduce the Bug

1. Create a clean DB Graph on a refreshed browser
2. Go to task tag property (ctrl+K search task)
3. Add property "Area" by going to configure -> Add property
![image](https://github.com/user-attachments/assets/2d0bf447-08fc-4a36-874e-cfa8585e7456)
4. Type name, pick new option and text
![image](https://github.com/user-attachments/assets/d2432a8f-82ef-4ff2-a81c-23a704f645a7)
5. Back to Task properties
![image](https://github.com/user-attachments/assets/a75f0115-d62b-470c-9fd3-de23c8b11c60) 
6. Click on Area to change it's configuration
![image](https://github.com/user-attachments/assets/a5980047-76a5-454d-871f-b0b9bf8e119d)

### Expected Behavior

Edit window pops up, like it does for existing properties

![image](https://github.com/user-attachments/assets/426d8c3e-3387-4a03-a0cc-a213b339d966)

### Browser, Desktop or Mobile Platform Information

Windows 10, MS Edge Version 127.0.2651.98 (Official build) (64-bit)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by logseq-cldwalker** [comment]
Hi. A fix has been pushed and should be up on test.logseq.com in about ~10m

**Comment by Zyrohex** [comment]
@logseq-cldwalker - this is resolved now for me. Thanks!

**Comment by logseq-cldwalker** [comment]
@bgrolleman I'm closing this as this seems to be fixed. Feel free to reopen if it's not
