### ISSUE TITLE
Node reference that contains a softline break and tag breaks the node reference

### ISSUE THREAD

**Issue by Zyrohex** [logseq/db-test#40]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When creating a node reference to an existing block that contains a softline break and a tag associated to that node, the node reference breaks and is not able to establish a link to the node.

### Reproduce the Bug

1. Create a block
2. Copy and paste the example I have listed below into the block
```markdown
- **Test** 
  This is a test
```
3. Tag the block with `#Concept`
4. Now create a new node and try referencing the previous node you created and notice after clicking outside of the node that it fails to establish a link or render the node.

### Expected Behavior

Creating a node reference that contains a softline break and a tag should not break the node reference.

### Screenshots

![chrome_vPVsxULQk1](https://github.com/user-attachments/assets/ccb06169-a04d-4b7d-bc08-3981559cd13b)

### Browser, Desktop or Mobile Platform Information

Logseq DB Test Environment
Commit = https://github.com/logseq/logseq/commit/187fa1d

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
@Zyrohex Can you confirm whether it works for you?

**Comment by Zyrohex** [comment]
@tiensonqin - this one is resolved! Thanks
