### ISSUE TITLE
Tag is constantly removed when changing

### ISSUE THREAD

**Issue by bgrolleman** [logseq/db-test#41]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

I was setting up a test structure and adding the \#video tag, this is child tag of \#task as videos have a similar workflow and I want to see them in the now view. 

For some reason, the test item I made (Aug 25th) keeps losing it's video tag when I make changes

### Reproduce the Bug

1. Go the the 25th
2. Make sure the Logseq DB Alpha line has the video tag
3. Try changing a few properties like published date
4. Watch tag get removed 

### Expected Behavior

Once I put a tag somewhere I expect it to stay put unless I manually remove it.

### Screenshots

https://github.com/user-attachments/assets/55cb7d89-35eb-4fd3-b1b5-aeaf211d7b73

### Browser, Desktop or Mobile Platform Information

Win 10, MS Edge latest version

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by bgrolleman** [comment]
SQlite Export of the graph I'm using here

[logseq_db_Structures Test_1724565949.zip](https://github.com/user-attachments/files/16739167/logseq_db_Structures.Test_1724565949.zip)

**Comment by bgrolleman** [comment]
Other details on what I did, created the video tag, made task parent and added the status property to the video tag so it shows up in the table

**Comment by tiensonqin** [comment]
@bgrolleman Thanks for the report! Unfortunately, I can't reproduce this bug with your exported sqlite file. 
Can you get the revision by clicking General > Current version 0.10.10?

@logseq/core Can anyone else reproduce this bug?

**Comment by bgrolleman** [comment]
@tiensonqin - Current Revision: [a1c56c0](https://github.com/logseq/logseq/commit/a1c56c0)

Weird that it can't be reproduced, I tried making a new tag (Project) and that works fine, Task is fine. Just video that disappears all the time. I need to start my workday but will make a note to see if I can export any other debug information this evening and maybe reproduce it in a fresh graph while writing down the steps.

**Comment by bgrolleman** [comment]
I tried to simulate the issue, but I think it's gone now that things open in the menu by default. (I'm not sure if this is the new default but I do like it from a consistency sake.)

Close ticket for now
