### ISSUE TITLE
Node References from Tables do not apply markdown rendering

### ISSUE THREAD

**Issue by Zyrohex** [logseq/db-test#42]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When creating a block reference from a node that's stored in a tags table, the node reference does not apply markup rendering on the block like you would expect, or see from a normal node.

### Reproduce the Bug

1. Create a tag
2. Navigate to the tag page
3. Create a new entry in the tag's table and add some MD formatted = `**Lazy Evaluations:** Used as a means...`
4. In the notes section create a node reference to the block you created in the table.
5. Notice the node reference displays the markup formatting in the text instead of applying MD rendering

### Expected Behavior

Node references from a node that's stored in a tags table should render the same as a regular node

### Screenshots

![image](https://github.com/user-attachments/assets/17fdf20d-a19e-49d2-89f0-1ebc89eef98c)

### Browser, Desktop or Mobile Platform Information

Logseq DB Test Version

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by Zyrohex** [comment]
More context - this is not strictly only nodes that are in a table. These look to be tied to those which have a tag associated to the block.

**Comment by tiensonqin** [comment]
This should be fixed now, it'll take 10m to update test.logseq.com.

**Comment by Zyrohex** [comment]
@tiensonqin - this one is also resolved. Thanks
