### ISSUE TITLE
Node references do not appear on blocks that contain a tag unless they are specified in a node schema property

### ISSUE THREAD

**Issue by Zyrohex** [logseq/db-test#43]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Adding node references to a block that contains a tag does not show the block references, even though the targeted block shows the red indicator incrementing with each reference created.

### Reproduce the Bug

1. Create a tag called "#CNC"
2. Add the Description Property
3. Add a second property called "Related" and set it to a schema type of "Node" with multiple values checked
4. Navigate to your journal page and create a new block - name it whatever you want but you do not need to specify any tags on the block.
5. Open this block in the right side panel so you can keep an eye on the changes
6. Now create a second block in your journal page -- name it whatever and then create a node reference to the previous node you created.
7. Make note that the node reference appears in the side panel for that block
8. Now on the second block add the tag "#CNC" and make note that the node reference now disappears from the reference section in the side panel.
9. Add the node reference back to the second block in the "Related" property and make note that the reference now appears again in the side panel.

### Expected Behavior

Node references should always be visible regardless of where they are defined on a block that contains a tag.

### Screenshots

https://github.com/user-attachments/assets/c56d3df5-4b37-4f73-8747-6ac9dcf8a187

### Browser, Desktop or Mobile Platform Information

Logseq DB Test Version

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by Zyrohex** [comment]
Bit more context to this. This appears to only affect node references, page and tag references work as expected.

**Comment by tiensonqin** [comment]
Thanks for the report! https://logseq-db-demo.pages.dev/#/ will be ready in 10m.

**Comment by Zyrohex** [comment]
This is resolved!
