### ISSUE TITLE
Node page reference lookup from a property does not display the corresponding tags for pages

### ISSUE THREAD

**Issue by Zyrohex** [logseq/db-test#44]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

While adding metadata to properties I noticed that using a schema type of "Node" and performing a lookup does not display the tags that are associated with pages. This makes it very difficult to determine which page you want to associate a property with and requires a bit of guess work and toggling back and forth.

### Reproduce the Bug

1. Create two pages called "Bat" but assign each page separate tags "#Baseball" and "#Animal"
2. Create a tag called "#Concepts"
3. Create a property called "Subject" and assign it the node schema type
4. Create a block and tag it with "#Concept"
5. In the related property type in "Bat" and make note that the results you get back only display the page name but do not mention what tags are associated with the page

### Expected Behavior

The node lookup frame should display the tags associated with a page just as if you were doing a normal node reference lookup in a regular block.

### Screenshots

https://github.com/user-attachments/assets/4a90c2e3-f660-4ed5-a299-ed34666afcd7

### Browser, Desktop or Mobile Platform Information

Logseq DB Test Version

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by logseq-cldwalker** [comment]
Hi. Thanks for noticing this. Displaying uniqueness of nodes or objects could be improved so please do continue to file issues on where it can be improved. This fix should be up on test.logseq.com in ~10m

**Comment by Zyrohex** [comment]
@logseq-cldwalker - I am keeping an eye out of those things and looking for inconsistencies. I did test and its working as expected now. There's only a slight inconsistency where references in the node schema will always display the page name + tag name after exiting the editor vs a normal reference will hide the tag name when you exit out of the editor.

Example:
![image](https://github.com/user-attachments/assets/89d46902-4d5c-4eee-a82c-84f405367518)

VS normal node references:
![image](https://github.com/user-attachments/assets/2457b595-2c76-4208-a726-1ef4c2237ccb)

**Comment by logseq-cldwalker** [comment]
Glad it works. I'd recommend a separate issue for normal node references as that change would affect a lot more features and could require some discussion
