### ISSUE TITLE
Tag Properties values are not editable

### ISSUE THREAD

**Issue by Bad3r** [logseq/db-test#45]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When adding a tag property to a #tag its not possible to set a value

### Reproduce the Bug

Tested on https://test.logseq.com

1. Create a tag `#test`
2. Inside the tag 'page' add a tag property. Example `Description`
  i. ![image](https://github.com/user-attachments/assets/c125815c-83d4-44db-9518-bfff87bcb753)
3. Attempt to set a value to it either from the creation prompt or after creating it
4. The value field is uneditable

**Comment by Bad3r** [comment]
I understand that this might be intended but it would be useful if we can also add values to properties to tags like description

**Comment by logseq-cldwalker** [comment]
Hi. A tag's block/node properties can be set as described in https://github.com/logseq/db-test/issues/46#issuecomment-2324937800. The properties you are editing are tag properties which are inherited by every node that uses the new tag. I recommend reading all of the [new tags section](https://github.com/logseq/docs/blob/feat/db/db-version.md#new-tags) if you haven't already. Does this make sense?

**Comment by Bad3r** [comment]
> Does this make sense?

It does make sense. I just think that it would be very useful to be able to add, for example, a `description` property to a tag with a description (value) to provide more context to the tag. Another example is an alias. For example, `#NIST` has the alias `National Institute of Standards and Technology`. I think it provides a better user experience and allows for a better tag experience, especially in the future when sharing graphs.

**Comment by logseq-cldwalker** [comment]
>  I think it would be very useful to add a value to the parent tag while inheriting only the property without the value, for example, a description property to a tag with a description (value), to provide more context to the tag.

You can already do this as described in https://github.com/logseq/db-test/issues/46#issuecomment-2324937800. Pages and blocks have the same behavior for adding properties to themselves. Gonna close as there isn't anything to fix. If you have more questions on ux, perhaps start a chat discord thread to see if others share similar questions
