### ISSUE TITLE
Free form writing in a tags table window causes the cursor to loose focus when using a property key named "Description"

### ISSUE THREAD

**Issue by Zyrohex** [logseq/db-test#5]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

While trying to add new nodes from the Tag page, from inside the table view that displays the references to the tagged nodes, free form writing such as one you would use for a property called "Description", results in the cursor loosing focus after pressing any key on the keyboard.

### Reproduce the Bug

1. Create a tag class
2. Open the tag class page
3. In the table view - click on add new property and name it "Description"
4. Make note: When you create the property with a capital D, the result is you get a lowercase property key instead.
5. Now create a new node from inside the table view, then for the description property, try typing anything in this block and note how the cursor looses focus after pressing a single key stroke.

### Expected Behavior

The description block should behave as one would expect. It sounds like description is a default class name defined in Losgeq so when you try to create this property, it defaults to the already existing class, but then runs into this bug.

### Screenshots

https://github.com/user-attachments/assets/9c775901-32f1-4ab6-b625-4887c0563cbd

### Browser, Desktop or Mobile Platform Information

Logseq DB Test Environment
Revision = https://github.com/logseq/logseq/commit/046e81b

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by Zyrohex** [comment]
Hrm.. This one may not be quite straight forward. I tried replicating again on a fresh DB graph but i'm not able to reproduce now. I'll have to do some testing and see if I can figure out what triggered that bug.

**Comment by Zyrohex** [comment]
I have run into this issue once more, but it was completely random and it was not at any particular time when I was adding a new property, it was an existing property. So the condition is not centered around when a property is defined or created. Still not entirely sure what it is but i'll continue to keep an eye out and see if I can pin point it.

**Comment by tiensonqin** [comment]
I'm able to reproduce this bug when opening the same page in the right sidebar. I'll push a fix soon.

**Comment by tiensonqin** [comment]
@Zyrohex I just pushed a fix, let me know if it works for you.

**Comment by tiensonqin** [comment]
Btw, `description` is a built-in property, there're some limitations that we'll relax soon, like being able to change its name.

**Comment by Zyrohex** [comment]
@tiensonqin - nice! I have not been able to replicate with the same page opened in the right sidebar. I think we can call this one resolved.
