### ISSUE TITLE
Adjacent property values shift their location when they contain child nodes and the user uses the backspace key to delete all the content inside of a property

### ISSUE THREAD

**Issue by Zyrohex** [logseq/db-test#50]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When deleting the last node for a property I noticed that instead of the property return to a state where it displays "Empty" for its values, it instead will shift a node that's in a property above the currently focused property down 1 level, leading to nodes being shifted into a completely different property domain.

### Reproduce the Bug

1. Create a tag with the following two properties that are both text nodes "Description & Details"
2. Create a page and tag it with the tag you created in step 1
4. Add some notes to the Description property and be sure to include some child nodes
5. Add some notes to the Details property.
6. Now click inside the text node for the Details property - press CTRL+A to select all and press the back space key twice. This should reset the node to a state of being Empty, however, instead what happens is the child node above this property gets shifted down.

### Expected Behavior

Deleting the content in a property should not cause adjacent property values to shift their location

### Screenshots

https://github.com/user-attachments/assets/3068e616-7953-4194-8183-20eb4d99eb6b

### Browser, Desktop or Mobile Platform Information

Logseq DB Test Environment

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by Zyrohex** [comment]
Bit more context - this also happens when a property is configured to use multiple values and you have an adjacent node above the one you are deleting that contains a child node.. After deleting the bottom node, the child node from above is shifting up one level.

https://github.com/user-attachments/assets/0a62f0ce-841f-4e4f-96b9-fe09a905f60e

**Comment by tiensonqin** [comment]
@Zyrohex I just pushed a fix, let me know whether it works for you.

**Comment by Zyrohex** [comment]
@tiensonqin - this is resolved, thanks!
