### ISSUE TITLE
Right clicking on a page property node does not list options for the node but instead gives options for the page instead

### ISSUE THREAD

**Issue by Zyrohex** [logseq/db-test#51]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Went to right click on a node's bullet so I could select to delete the node but noticed I instead only had options that were tied to the page. Looks like it's using the context menu that you get when you right click on a page title. 

### Reproduce the Bug

1. Create a page
2. Add any text node property to the page
3. Click inside the node and add some text
4. Right click on the node's bullet and notice you do not get the options menu you would typically expect for a node

### Expected Behavior

Right clicking on a node's bullet should list properties for that node and not the page

### Screenshots

https://github.com/user-attachments/assets/71ecca6b-6895-4713-827a-32be9299df53

### Browser, Desktop or Mobile Platform Information

Logseq DB Test Environment

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by logseq-cldwalker** [comment]
Hi. Put up a fix that'll be up on https://logseq-db-demo.pages.dev/ in ~10m. I fixed it for the case you mentioned where the page property is `Text`. When the page property is another type e.g. Number or Node, do you expect the right click menu to not display? That's the behavior when on a block. When on page, those property types still show the page context menu

**Comment by Zyrohex** [comment]
@logseq-cldwalker - Awesome I will check it out in a bit.

I agree, there's no need to list the menu for enumerates lists. It would only lead to confusion if they were to try and choose a header or the num list option.

**Comment by Zyrohex** [comment]
Looks like its resolved and working as expected- thanks!
