### ISSUE TITLE
Node icon duplicated

### ISSUE THREAD

**Issue by hdansou** [logseq/db-test#53]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

On a node, when I use the keyboard shortcut p+i, and then select an icon, two icons show up in front of the node.
The one on the right side is changeable.

### Reproduce the Bug

https://github.com/user-attachments/assets/a6a95a66-8dab-4692-a9bb-69274c56eae2

### Expected Behavior

One icon, that can be changed/replaced as needed

### Screenshots

https://github.com/user-attachments/assets/a6a95a66-8dab-4692-a9bb-69274c56eae2

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
@logseq/core Can anyone reproduce this bug?

**Comment by logseq-cldwalker** [comment]
@tiensonqin I can't reproduce on [f2ff8bf](https://github.com/logseq/logseq/pull/9858/commits/f2ff8bf26b80b34fdeae417286ab2528e223c8a8)

@hdansou Can you reproduce this on a new graph? What exact test version are you on? You can find the exact version by pressing `t s` and clicking on the version 0.10.0 link. A notification pops up the exact version you're on

**Comment by hdansou** [comment]
@logseq-cldwalker I can only reproduce the error on an imported sqlite file that was exported two weeks ago. The issue is not present when I create a new graph. We can close this issue.
