### ISSUE TITLE
Unable to create a page with a tag from a block [[page #tag]]

### ISSUE THREAD

**Issue by Bad3r** [logseq/db-test#54]
### What Happened?

The new feature to add a page with a tag, for example, CMD+k `page name #pagetag`, is useful. Sometimes, I want to do the same while editing a block, but it doesn't work.

### Reproduce the Bug

Steps to reproduce:
1. In a block type [[]]
2. between the brackets, attempt to create a page with a tag, e.g., `[[pagename #pagetag]]`
3. Press enter
4. The page tag will disappear

**Comment by tiensonqin** [comment]
Try `[[pagename]]#pagetag` instead.
[[pagename #pagetag]] is not supported because it requires users to input the exact pagename and pagetag, the UX is complex too. That said, we might revisit this someday if there're better ways to handle this.
