### ISSUE TITLE
Paste multi-line text into to a text property value fails

### ISSUE THREAD

**Issue by Bad3r** [logseq/db-test#56]
### What Happened?

I am unable to reliably reproduce this issue, but I tested it on test.logseq.com in a new graph and new block, and the bug occurred.

Sometimes, reloading the page or the graph makes the text appear again; sometimes, after adding it the first time, it works as expected on the second attempt.

### Reproduce the Bug

1. Create a block of text
2. Add a text property, for example, `Description`
3. Paste or write a multi-line description in the text value field
example:
a. block with the text:
```
Repellendus harum ratione quidem maiores nihil. Nesciunt omnis aut et.
```
b. Add the description property
c. in the field value, add the following
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, 

+ Ullus investigandi veri, nisi inveneris, et quaerendi defatigatio turpis est,
+ Ullus investigandi veri, nisi inveneris, 
+ et quaerendi defatigatio turpis est, 
```
d. Exit edit mode without pressing Enter
F. If the value text disappears, reload the page or CMD+r

This also works without the bullet point `+` usage; it doesn't work only when pasting. It will also happen if you write a multi-line description.

You might need to try a couple of times, each with a new block or a new graph.

**Comment by tiensonqin** [comment]
@logseq/core let me know if anyone can reproduce this one 🙏

**Comment by tiensonqin** [comment]
@logseq-cldwalker Can you still reproduce this bug locally?

**Comment by tiensonqin** [comment]
I'm going to close this one, I can re-open it if anyone can still reproduce this bug.
