### ISSUE TITLE
Referencing a quoted block that contains a tag breaks quote formatting

### ISSUE THREAD

**Issue by Bad3r** [logseq/db-test#57]
### Steps to reproduce:
1. create a quoted block 
```
> Quam voluptate inventore qui expedita a magni sed. Non tempora adipisci illum consequatur consequuntur.
```
2. add a tag to the block `#tag1`
3. reference the block `[[block-ID]]` in another block
4. notice that the block is embedded without the quote block style

**This issue does not affect quote blocks without a tag.**
![image](https://github.com/user-attachments/assets/3b091db9-fab7-4c4f-9d20-c03d817404ad)

**Comment by tiensonqin** [comment]
Closing now since #quote block has been introduced.
