### ISSUE TITLE
sqlite export doesn't include "contents"

### ISSUE THREAD

**Issue by blogbourri** [logseq/db-test#59]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

when i export a sqlite backup and then import it, the table of contents ("Contents" in the sidebar) is de-populated

### Reproduce the Bug

1. make a new graph, "clean"
2. open the sidebar and type "table of contents" into the "Contents"
3. export graph to sqlite
4. import sqlite backup as a new graph, "clean import"
5. "Contents" is empty

### Expected Behavior

contents shouldn't be wiped

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
I just pushed a fix, let me know whether it works for you.
https://logseq-db-demo.pages.dev will be updated in 10m.

**Comment by tiensonqin** [comment]
@logseq/core Can anyone reproduce this bug?

**Comment by blogbourri** [comment]
this can be closed, at some point it started working. i probably just forgot to clear cache or something and didn't see the fix work initially.
