### ISSUE TITLE
Clearing the search box for setting node icons, delete nodes

### ISSUE THREAD

**Issue by hdansou** [logseq/db-test#62]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

- When setting the node icon, it sometimes leads to node(s) deletion

### Reproduce the Bug

	- Steps
		- Set a node with nested nodes
		- While setting the icon to the parent node
			- Search for an icon by typing the keyword to search with
			- then press the backspace key to erase the text; this leads to node deletion
			- all nested nodes are removed

### Screenshots

https://github.com/user-attachments/assets/c570c615-5103-4e13-9f22-64151c52d9aa

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
Thank you for the report!
https://logseq-db-demo.pages.dev/ will be updated in 10m, let me know if it works for you.
