### ISSUE TITLE
Checkbox truncated

### ISSUE THREAD

**Issue by hdansou** [logseq/db-test#63]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Using a property with type checkbox is truncated when placed at the end of the Journal block 

### Reproduce the Bug

1. Add a property meditation to the `#journal` tag
2. Position the property at the end of the block
3. Observe the truncated checkbox

### Screenshots

![image](https://github.com/user-attachments/assets/96c6554e-5e48-40fb-8f3b-82276b579c0d)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
@xyhp915 Is it fixed?

**Comment by xyhp915** [comment]
> @xyhp915 Is it fixed?

Yes. It's fixed with my test.

**Comment by tiensonqin** [comment]
Ok, closing this now. 
@hdansou I can re-open this issue if it doesn't work for you.
