### ISSUE TITLE
CMD+p shortcut does not work as expected in Linux/Windows

### ISSUE THREAD

**Issue by Bad3r** [logseq/db-test#64]
### What Happened?

The CMD + p shortcut does not work for adding properties on Windows and Linux. Instead, it jumps to the start of the block or the block above.

Tested on test.logseq.com and multiple users were able to verify the issue.

### Reproduce the Bug

1. press cmd + p to add a property on linux or windows

**Comment by tiensonqin** [comment]
@Bad3r It's `ctrl+alt+p` on Windows and Linux.
