### ISSUE TITLE
DB Version: cannot click on today's date in date picker pop-up

### ISSUE THREAD

**Issue by nckre** [logseq/db-test#65]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Cannot click on today's date in the date picker popup. 

### Reproduce the Bug

1. Tag page (e.g. #Task)
2. Chose date property (e.g. Deadline)
3. Try clicking the current date

### Screenshots

![CleanShot 2024-09-09 at 11 54 07](https://github.com/user-attachments/assets/7b65ee7c-96b4-4593-a937-9bba4ca170c2)

### Additional Context

Workarounds: 
1. Click on other date (e.g. yesterday), then clicking current date works
2. Hit enter on keyboard (that's what I did in the gif)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by logseq-cldwalker** [comment]
QAed and confirmed this works. Closing as this was fixed 2 days ago

**Comment by artemith** [comment]
@logseq-cldwalker @xyhp915 This issue appears again.

**Comment by artemith** [comment]
> @artemith Hi. I'm able to reproduce. Pushed up a fix and should be up on test.logseq.com in ~10m. Let me know if it works for you

@logseq-cldwalker Hi, this works for me. Thanks!
