### ISSUE TITLE
Order of tag application has different outcomes when checking for uniqueness

### ISSUE THREAD

**Issue by nckre** [logseq/db-test#66]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Writing a node and then applying a tag has a different outcome than first applying the tag and then writing the node. Both should be the same.

### Reproduce the Bug

1. Assign a tag to an empty node (e.g. #Task)
2. Fill the node content (e.g. "hello")
3. Assign the same tag to another empty node
4. Fill that node with the same content
→ This will lead to an error message ("Another block named "hello" already exists for tag "Task").

Do the same in a different order:

1. Fill the node
2. Assign tag
3. Fill another node with same text
4. Assign same tag
→ No error message

### Expected Behavior

Both should have the same behaviour. 

### Screenshots

![CleanShot 2024-09-09 at 22 02 55](https://github.com/user-attachments/assets/9350946f-ddcc-450a-ac50-9cdd04546a75)

[test.logseq.com-1725908742371.log](https://github.com/user-attachments/files/16935355/test.logseq.com-1725908742371.log)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by logseq-cldwalker** [comment]
Hi. Good catch. A fix for this should be up on test.logseq.com in about ~10m

**Comment by nckre** [comment]
@logseq-cldwalker can I see the exact build I'm using somewhere? Can still replicate the bug after a hard refresh + new graph. Settings show "0.10.10" but that seems some larger, old release.

**Comment by nckre** [comment]
Ok, seems like I'm on the latest ([7b3fa77](https://github.com/logseq/logseq/commit/7b3fa77)) and can still replicate this.

**Comment by logseq-cldwalker** [comment]
Ah. Missed a 2nd case. Fix should be up on test in ~10m

**Comment by nckre** [comment]
Can't reproduce any more 👍

**Comment by nckre** [comment]
Btw. don't want to start another thread here @logseq-cldwalker but do check this: https://discord.com/channels/725182569297215569/1282266595418439690

While the behavior is consistent now, I'm not convinced that all objects should have a unique name.

It's useful not to accidentally duplicate unique objects (e.g. `A New Hope #movie`) but think e.g. of tasks:
Right now, can only have a single `Buy milk #Task` in your graph. Need to buy milk more often.

**Comment by logseq-cldwalker** [comment]
Yep. I'm aware of the thread and hope to address soon
