### ISSUE TITLE
Clicking on journal heading shouldn't edit it since it is uneditable text

### ISSUE THREAD

**Issue by nckre** [logseq/db-test#67]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

In DB version clicking on Journal heading enters text edit (but cannot save).

In MD version, clicking on Journal heading would forward to that page.

### Reproduce the Bug

1. Go to "Journals"
2. Click on heading (e.g. "Sep 10th, 2024")
3. Edit text

### Expected Behavior

Same as MD version, i.e. open the relevant page.

### Screenshots
DB Version
![CleanShot 2024-09-10 at 09 52 32](https://github.com/user-attachments/assets/db8b55a1-64ba-4590-b895-affd51148bc1)

MD Version
![CleanShot 2024-09-10 at 09 53 51](https://github.com/user-attachments/assets/cb7ddd26-4b7f-467d-93bb-de1fb03f5b9f)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by logseq-cldwalker** [comment]
Being able to edit any page title with a click is intentional and documented in https://github.com/logseq/docs/blob/feat/db/db-version-changes.md#pages. Is the issue that uneditable titles shouldn't be clickable in such a way?

**Comment by logseq-cldwalker** [comment]
Fixed with https://github.com/logseq/logseq/pull/9858/commits/89cbd131d0073c2a744756eab1fe3572c9bc36a8 and then a followup commit for when on the journal page itself. Should be up on test.logseq.com in ~10m

**Comment by nckre** [comment]
@logseq-cldwalker works, but cursor prop doesn't change -> should be set to pointer?
