### ISSUE TITLE
Cannot save property name when editing heading

### ISSUE THREAD

**Issue by nckre** [logseq/db-test#68]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When clicking on the heading of a property, you can edit the text but upon hitting enter it does not save.

You can change the name of a property via the dropdown menu.

### Reproduce the Bug

1. Create a custom property
2. Go to the page of the property
3. Edit the heading

### Expected Behavior

Editing the heading should either be disabled or save the new name

### Screenshots

![CleanShot 2024-09-10 at 10 48 09](https://github.com/user-attachments/assets/9cded97b-595d-4ab5-91d9-2b3c16cded77)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
This should be fixed by https://github.com/logseq/logseq/commit/4cdedf754eac848a65f38bd726802f71c08bbb70.
