### ISSUE TITLE
No unique check for property name

### ISSUE THREAD

**Issue by nckre** [logseq/db-test#69]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Not sure if this is a bug, but current behaviour is inconsistent.

When assigning a property, there is a check for unique name. If the name is exactly the same (incl. capitalization) I'm not offered to create a new property with the same name.

![CleanShot 2024-09-10 at 10 59 34](https://github.com/user-attachments/assets/d4f815dc-4abd-434a-b626-b5c03b9cc514)

When changing the name of a property, I can chose an existing name though. So there can be two properties with the same name and type.

![CleanShot 2024-09-10 at 11 01 48](https://github.com/user-attachments/assets/51a76c25-76e5-4402-88c5-868c099d791f)

If it's ok to have multiple properties with same name & type, should offer to create a property also when assigning. 

If it's not ok, should introduce some unique check when re-naming the property.

### Reproduce the Bug

1. Go to existing property
2. Click on `Configure Property` and change name to another property (e.g. `Status`)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by logseq-cldwalker** [comment]
Hi. Good catch. Pushed up a fix to test and should be ready in ~ 10m

**Comment by nckre** [comment]
Works, but there are two error messages, I assume the unexpected webworker issue shouldn't be visible 👇 

![CleanShot 2024-09-11 at 09 09 27@2x](https://github.com/user-attachments/assets/12dfda1c-6a42-41b7-bac7-df163a5fb752)

[test.logseq.com-1726034986714.log](https://github.com/user-attachments/files/16958669/test.logseq.com-1726034986714.log)

**Comment by nckre** [comment]
Hard to take a screenshot that has the error messages, best test yourself.

Upon initial save, I can see both this well-formatted one and the #error from above

![CleanShot 2024-09-11 at 09 12 37@2x](https://github.com/user-attachments/assets/06e8660c-16e0-468f-9415-8668632d3ab6)

**Comment by nckre** [comment]
One more thing regarding system props, I can still create new props with these names (but not rename existing props to system props):

![CleanShot 2024-09-11 at 11 55 03](https://github.com/user-attachments/assets/42f61f40-ec6f-4e4a-9ca2-f46ef404e35c)

**Comment by logseq-cldwalker** [comment]
Good catches. There should be fixes for both cases on test.logseq.com in ~10m

**Comment by nckre** [comment]
Works, cannot see red #error any more + can now re-name existing props to system props
