### ISSUE TITLE
Nodes with multiple reference aren't replaced correctly upon deletion of references

### ISSUE THREAD

**Issue by nckre** [logseq/db-test#71]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When deleting a block that's referenced, the references usually turn into the original text.

That doesn't seem to work when a line has multiple references and they are all deleted.

### Reproduce the Bug

1. Indent two nodes
2. Write a new node with references to both of the above nodes
3. Delete both nodes from step (1) 

### Expected Behavior

Text for parent node should also be replaced.

### Screenshots

![CleanShot 2024-09-10 at 14 55 17](https://github.com/user-attachments/assets/126f91e5-88a3-4601-904f-4726a328b839)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
Thank you for reporting this unique issue! The website will be updated after 10m.

**Comment by tiensonqin** [comment]
Thank you for reporting this unique issue! The website will be updated after 10m.

**Comment by nckre** [comment]
Fixed
