### ISSUE TITLE
Current task status box should be DOING instead of NOW

### ISSUE THREAD

**Issue by nckre** [logseq/db-test#74]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

As per [description of new tasks](https://github.com/logseq/docs/blob/feat/db/db-version.md#tasks): "_The TODO/DOING and NOW/LATER workflows have been merged into TODO/DOING_" 

The dynamic box still shows "NOW", should be "DOING" (and probably replace hammer with half-fill circle?)

![CleanShot 2024-09-11 at 09 23 01@2x](https://github.com/user-attachments/assets/6ca52cc7-f799-4a04-8299-73c935bc1f70)

### Reproduce the Bug

1. Create task
2. Set task to status `Doing`

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by logseq-cldwalker** [comment]
Hi. Agree it would be nice for default queries to be consistent with task states. Should be up on test.logseq.com in ~10m
