### ISSUE TITLE
Previous journal pages and their blocks should have create-at timestamp for their journal date

### ISSUE THREAD

**Issue by babygaogao** [logseq/db-test#77]
### Search first

- [x]  I searched and no similar issues were found

### What Happened?

The inability to import past diaries is an important issue. Logseq's database version cannot import old logs by time, making data management difficult and hindering the handling of previous tasks and content. 

### Reproduce the Bug

Additionally, it is not possible to manually create logs with past dates, nor can users modify the creation dates in the database. There should at least be an option to allow users to modify the creation date of diary pages or to enable the import of old diaries, with timestamps automatically recorded based on the log page name, without needing to specify minutes and seconds.

![image](https://github.com/user-attachments/assets/66838b31-dfde-4c25-a71c-9d207c4d24bc)

**Comment by logseq-cldwalker** [comment]
Hi. Sorry for the delay

> The inability to import past diaries is an important issue. Logseq's database version cannot import old logs by time

It's unclear what issue you're encountering as journals are importing as shown by your screenshot. Is the issue that the journal's created-at is wrong for some journals e.g. 2020/03/30 journal should have a 2020/03/30 created-at?

> to enable the import of old diaries, with timestamps automatically recorded based on the log page name, without needing to specify minutes and seconds.

We could have a journal's created-at match the journal date _if_ there is content in the journal. If there isn't content in the journal then that would be incorrect as the journal was created when it was referenced. Since previously Logseq didn't capture when a file was referenced it would need to be set to the current import time

**Comment by logseq-cldwalker** [comment]
Closing because of lack of response. Feel free to reopen with answers

**Comment by babygaogao** [comment]
> Hi. Sorry for the delay
> 
> > The inability to import past diaries is an important issue. Logseq's database version cannot import old logs by time
> 
> It's unclear what issue you're encountering as journals are importing as shown by your screenshot. Is the issue that the journal's created-at is wrong for some journals e.g. 2020/03/30 journal should have a 2020/03/30 created-at?
> 
> > to enable the import of old diaries, with timestamps automatically recorded based on the log page name, without needing to specify minutes and seconds.
> 
> We could have a journal's created-at match the journal date _if_ there is content in the journal. If there isn't content in the journal then that would be incorrect as the journal was created when it was referenced. Since previously Logseq didn't capture when a file was referenced it would need to be set to the current import time

hi，We need to import old Logseq data, and many previous diaries have recorded a lot of blocks. Ideally, both the diary page from 2021/03/31 and the timestamps of the blocks on that page should have a creation date of 2021/03/31, instead of being marked with the timestamp of when the new database version is imported. The current issue with Logseq's database is that it recognises all the imported past data as being created on the day it was imported, which makes it hard to manage old data. Plus, there are still so many other mates who need to migrate their data. We hope this issue can be fixed because even manually going through each diary to address this problem isn’t feasible. We need your help, thanks!

**Comment by logseq-cldwalker** [comment]
@babygaogao I agree this would be helpful for managing older journals. I've updated the importer so that journal pages and blocks have the created-at timestamp of their journal day. This should be available on test.logseq.com in ~10m. Let me know if you're seeing the enhancement

**Comment by logseq-cldwalker** [comment]
@babygaogao Closing as this is done and haven't heard back

**Comment by babygaogao** [comment]
> @babygaogao I agree this would be helpful for managing older journals. I've updated the importer so that journal pages and blocks have the created-at timestamp of their journal day. This should be available on test.logseq.com in ~10m. Let me know if you're seeing the enhancement

well done！

**Comment by babygaogao** [comment]
> @babygaogao I agree this would be helpful for managing older journals. I've updated the importer so that journal pages and blocks have the created-at timestamp of their journal day. This should be available on test.logseq.com in ~10m. Let me know if you're seeing the enhancement

well done！
