### ISSUE TITLE
Deleting images from links

### ISSUE THREAD

**Issue by nckre** [logseq/db-test#78]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Two issues with deleting images from links:

1. Missing key in popup 
![CleanShot 2024-09-12 at 10 10 21@2x](https://github.com/user-attachments/assets/e515409c-6ddc-464e-8acd-580c39676ab1)

2. Cannot delete image from node reference (it does work from node embed)
![CleanShot 2024-09-12 at 10 14 34](https://github.com/user-attachments/assets/558d8c1b-64ac-4a36-bbba-3706b18c8586)

### Reproduce the Bug

1. Create an image link (e.g. `![Logo](https://avatars.githubusercontent.com/u/63385289?s=280&v=4)`)
2. Click on delete icon in image to see missing key
3. Reference node from (1) and click on blue delete icon in referenced image

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
@nckre Thanks for the report! Can you check whether it's fixed? Thanks!

**Comment by xyhp915** [comment]
> @tiensonqin popup with missing key is fixed, but can still not delete from node ref (build [3f3ab05](https://github.com/logseq/logseq/commit/3f3ab05))

Thanks for your feedback! It's fixed now.
