### ISSUE TITLE
Accessing date page from Graph View breaks Journals

### ISSUE THREAD

**Issue by nckre** [logseq/db-test#80]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When clicking on a date note from `Graph View`, I'm forwarded to a page without header. Upon clicking on `Journals` headers are not visible any more. 

![CleanShot 2024-09-12 at 10 45 43](https://github.com/user-attachments/assets/f18a58be-f88c-4ca2-af8f-5ef6d30dc635)

### Reproduce the Bug

1. Go to `Graph View`
2. Toggle `Nodes` -> `Journals`
3. Go to date page
4. Click on `Journals` in sidebar

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
A [fix](https://github.com/logseq/logseq/commit/23f8e9ca44536a1411fd5a29516578d920181f18) has been pushed, the website will take 10m to be updated. Let me know whether it works for you.

**Comment by nckre** [comment]
Can't reproduce any more
