### ISSUE TITLE
Hide `Search only current page` from search options when not on a page

### ISSUE THREAD

**Issue by nckre** [logseq/db-test#81]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Can trigger search from various non-pages (`Journals`, `Graph view`, `All pages`).

When clicking on "Search only current page" option, nothing happens.

![CleanShot 2024-09-12 at 11 01 29](https://github.com/user-attachments/assets/89771c9f-22fe-4456-badf-c8830b670ffb)

### Reproduce the Bug

1. Go to `Journals`
2. Open search
3. Click on `Search only current page`

### Expected Behavior

Should be either of these three: 
1. Not be visible
2. Give some results (e.g. on `Journals` search all journals)
3. Show an error

(1) seems the easiest

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
Fixed by https://github.com/logseq/logseq/commit/22c7f6747c2412d2afab79eb8b5f52b4d0591448.
