### ISSUE TITLE
Check for existing tags when converting page to tags

### ISSUE THREAD

**Issue by nckre** [logseq/db-test#82]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Tags are meant to be unique (getting error when trying to rename tag to existing tag).

If I convert a page to a tag, there is no check for uniqueness.

![CleanShot 2024-09-12 at 13 31 00](https://github.com/user-attachments/assets/064dd5f3-18cc-4664-8e1f-c91f958bbb4b)

### Reproduce the Bug

1. Create page [[Task]]
2. Convert page to tag via three-dot menu
3. Assign #Task and see two options

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
Fixed by https://github.com/logseq/logseq/commit/d463b64c788cf90604febbdda4b9c4bf71a86509.
