### ISSUE TITLE
Tables horizontal scrollbar doesn't work

### ISSUE THREAD

**Issue by gernalix** [logseq/db-test#84]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When I insert a big table with many columns, there's no horizontal scrollbar
![Logseq 2024-09-12 21-00-05~1](https://github.com/user-attachments/assets/23f48a06-627f-43b4-a5b1-4eb19a8c805c)

### Reproduce the Bug

1. create a table with many columns that can't be wrapped
2. press ESC to render the table
3. you can't scroll

### Expected Behavior

When I click on the scrollbar, I expect it to scroll the table horizontally, without going into edit mode
IN the desktop app v0.10.9 there is a scrollbar but it doesn't work, because when I click on it the table goes into edit mode (raw markdown code)

### Browser, Desktop or Mobile Platform Information

Windows 11, desktop app v0.10.9

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by xyhp915** [comment]
Fixed in DB branch: 

https://github.com/user-attachments/assets/eb6301ce-151b-4425-aef3-a66650c913e0

**Comment by gernalix** [comment]
> Fixed in DB branch:
> 
>  CleanShot.2024-09-13.at.12.08.20-converted.mp4

Will you also make the tables editable while they're rendered?

**Comment by tiensonqin** [comment]
@gernalix We will probably experiment with a rich-text editor in the future.
Closing this issue now.
