### ISSUE TITLE
Can't create page reference for today's date

### ISSUE THREAD

**Issue by nckre** [logseq/db-test#85]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Go to Journal (or any page) and try to create a page reference for today (e.g. `[[Sep 13th, 2024]]`).

Today's date doesn't show up in the dropdown and when hitting enter, nothing happens.

![CleanShot 2024-09-13 at 17 28 21](https://github.com/user-attachments/assets/2e856e9b-7c31-4286-bf4a-0eb47909f2ab)

### Reproduce the Bug

1. Write today's date in page brackets
2. Hit `Enter`
3. Nothing happens

### Additional Context

Workaround is to click out if the dropdown:

![CleanShot 2024-09-13 at 17 51 03](https://github.com/user-attachments/assets/b13c0ade-b018-46d5-84a8-ea638e192f94)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
I can reproduce that a block in today's journal page can't reference today's page, but I failed to reproduce it on other pages.
@nckre Can you still reproduce it? If so, I'll ask other team members to try to reproduce it.

**Comment by nckre** [comment]
@tiensonqin can't reproduce it anymore, today's date now shows up in dropdown and hitting `Enter` tags the page correctly
