### ISSUE TITLE
Changing page title inline doesn't happen immediately

### ISSUE THREAD

**Issue by nckre** [logseq/db-test#86]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

In the MD version, you could change a title inline and it would update immediately:

![CleanShot 2024-09-13 at 17 42 37](https://github.com/user-attachments/assets/18c874d5-79fd-4321-8457-27693484a145)

In the DB version, first need to click into the node for it to update:

![CleanShot 2024-09-13 at 17 44 46](https://github.com/user-attachments/assets/3c5303c5-1c9a-46be-a90a-309d9652c960)

### Reproduce the Bug

1. Page reference a note
2. Change the text in the node

### Additional Context

Would be nice if the suggestion in the dropdown would also be for the full title inside the brackets (currently it's only the text before the edit)

![CleanShot 2024-09-13 at 17 47 00@2x](https://github.com/user-attachments/assets/9c3ef784-15b5-44e4-a74e-18c34d217c4e)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by nckre** [comment]
@tiensonqin I can still replicate it consistently in the latest build:

1. Create inline page reference
2. Go to another block
3. Edit (1) inline
4. Click into another block

Recorded a `.gif` with clicks:

![CleanShot 2024-09-16 at 10 58 10](https://github.com/user-attachments/assets/ce7feda7-1a18-4066-ac29-00b3ac593b1b)

**Comment by tiensonqin** [comment]
@nckre Thanks, I can reproduce it now, it happens when clicking to another block.
I'll push a fix soon.

**Comment by tiensonqin** [comment]
@nckre The website will be updated afte 10m, let me know whether it works for you 🙏

**Comment by nckre** [comment]
@tiensonqin Yes, seems fixed.

Hope you had a good mid-autumn and the chance to eat some mooncakes, seems like you guys never stop working :)
