### ISSUE TITLE
Text duplication in blocks with a page link and a codeblock

### ISSUE THREAD

**Issue by Bad3r** [logseq/db-test#87]
I am not sure how to describe this issue but its easy to reproduce:
1. create a block with a page link e.g.
```
[[test01]]
```
2. Use Shift+Enter to add a codeblock to the same block
![image](https://github.com/user-attachments/assets/4d1c52d2-bd5c-46b3-ba5d-39956523df90)
3. Exit edit mode
4. Place the cursor in the start of the codeblock (Not in edit mode)
5. Add a `$` at the start of the code block (before `echo`)
6. The `$` will disappear
7. Enter edit mode; note that the codeblock line is now duplicated with the `$`:
![image](https://github.com/user-attachments/assets/1531f59b-2b65-4fbd-ac7f-9d15cfcf7b82)

Note that this issue only happens when there is a `[[page link]]` in the same block.
If you continue attempting to add the `$` the text will continue to duplicate overflowing to a new line.
![image](https://github.com/user-attachments/assets/636ee190-edd0-41b9-b5b0-a470a4715979)

**Comment by tiensonqin** [comment]
I just pushed a fix, the website will take ~10m to be updated.
