### ISSUE TITLE
Can delete default homepage

### ISSUE THREAD

**Issue by nckre** [logseq/db-test#89]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

There is a feature under `Settings` -> `Features` that allows to disable journals and use a custom default home page instead.

That page can be deleted without warning. 

`Journals` in sidebar then redirects to old journal pages even though setting is still toggled off. If old journals don't exist, clicking on the menu bar item doesn't do anything.

### Reproduce the Bug

1. Create page e.g. [[Home]]
2. Go to settings and turn default home page to page from (1)
3. Delete page from (1) 

### Expected Behavior

Either it should be forbidden to delete default home page or there should be a warning + `Journals` options should be switched back on.

### Screenshots

![CleanShot 2024-09-14 at 22 23 17](https://github.com/user-attachments/assets/59158ac1-657d-471a-8fd4-8106761b4bb8)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by nckre** [comment]
Just realized it already existed in MD version and has the same behaviour as described above. Probably not an important bug, mb just close it.

**Comment by tiensonqin** [comment]
>  Journals options should be switched back on.

Thank you for the suggestion! Deleting the home page will re-enable the journals feature now.
