### ISSUE TITLE
No way to remove an existing tag value from a page's properties when you define a new tag name that matches the name of an existing page reference

### ISSUE THREAD

**Issue by Zyrohex** [logseq/db-test#9]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When assigning a new tag value to a page and giving it the name of an existing page reference, the first thing no option appears to select the existing page reference, secondly when you choose to create the tag instance, instead of creating what I would expect to be a tag reference, it instead re-routes you to the page reference instead. This then leads to an issue where you cannot remove this page reference from the tag property key. One key thing that I have noticed in this issue is that you MUST define an alias name in order for this bug to show up.

### Reproduce the Bug

1. Create a page reference called "[[Class Test]]".
2. Open the page "Class Test" and define a new alias for the page called "Class Testing".
3. Now Create a new page, with a random name, and inside that page add some text.
4. Click on the configure option for the page.
5. Select the Empty cell for tags
6. Input the name "Class Test" that you created from step 1
7. Note that you have no option to select any existing page reference, so click create new option.
8. Now Click on the link from the properties for "Class Test" to navigate to this page.
9. Notice that it takes you to the page reference you created in step 1 and not a tag reference page.
10. Also notice that there are no references to that page you just added to the tag reference too.
11. Navigate back to your page that contained the tag reference.
12. Try clicking inside the tag cell so you can add/remove selections and notice that you do not have an option to remove this page reference.. Essentially causing the page to become stuck with this option unless you delete and re-create the page.

### Expected Behavior

When defining a tag reference in the tag property and an existing page reference exists with an Alias, I would expect it to still create the new tag reference and not point to the page reference instead.

### Screenshots

https://github.com/user-attachments/assets/bd782ee9-2c98-4377-a82b-7ba6b211c137

### Browser, Desktop or Mobile Platform Information

Logseq DB Test Version
Revision = https://github.com/logseq/logseq/commit/f39e626

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
I just pushed a fix https://github.com/logseq/logseq/commit/3aae90b7fbe9894e9b7c2b91933bb03bf4ced230.
@Zyrohex Let me whether it works for you. It might take ~10 minutes for https://logseq-db-demo.pages.dev/#/ to be ready.

**Comment by Zyrohex** [comment]
@tiensonqin - just refreshed and my instance shows its on commit = https://github.com/logseq/logseq/commit/3aae90b

But same issue for me here.

**Comment by Zyrohex** [comment]
It's an improvement - the page ends up being a tag page now, but it ends up converting the original node that was a type page to a type tag. Which if that's intentional then yeah its good. I was expecting it to create a separate node type of tag though. If it ends up staying this way, maybe display a warning that it's converting a page to a tag?

**Comment by tiensonqin** [comment]
We can probably introduce another option to create a new tag if a page with the same name exists.
So there'll be two options if a page exists, but it's not a tag:
1. convert this page to a tag
2. create a new tag with the same name

I'll give this a try later and close this issue for now.
