### ISSUE TITLE
Can delete built-in property from pageTags

### ISSUE THREAD

**Issue by nckre** [logseq/db-test#91]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Can remove `built-in?` property from pageTags page and afterwards delete built-in pages.

### Reproduce the Bug

1. Go to a page
2. Assign `pageTags` `built-in?`
3. Go to `built-in?` page
4. Delete pages from list

### Screenshots

![CleanShot 2024-09-15 at 21 29 21](https://github.com/user-attachments/assets/8c76e65a-84a0-4356-8121-36cc23a44e60)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by nckre** [comment]
Bin icon is removed, so can't replicate any more on that page.

The only other default pageTag that I found I can delete nodes from is this, not sure if problematic:

![CleanShot 2024-09-16 at 11 36 57@2x](https://github.com/user-attachments/assets/104601a8-9edf-4e26-aa3b-636e32f6c120)

**Comment by logseq-cldwalker** [comment]
Hi. Thanks for pointing out error states with modifying internal pages like built-in? and view-for. Navigating to internal pages like these has been disallowed
