### ISSUE TITLE
$$$favorites hidden in ctrl+f and all pages, but discoverable by query

### ISSUE THREAD

**Issue by blogbourri** [logseq/db-test#92]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

i came across a page, $$$favorites, while testing out queries. i believe it isn't supposed to be directly editable, but could be mistaken on that fact though.

### Reproduce the Bug

1. add a page to favorites
2. create a query to return blocks with page references to that page
3. one of the results will be on the $$$favorites page
4. $$$favorites can then be navigated to and edited directly, though doing so didn't seem to cause any problems

### Expected Behavior

i believe this page is meant to be hidden, and it might mean other similar pages are discoverable via query

### Screenshots

![image](https://github.com/user-attachments/assets/8f8b1c03-f398-43da-9fa0-a1181824b8bc)
![image](https://github.com/user-attachments/assets/65c25e31-10df-4352-a1ab-f8bcd46276a7)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by vonalbert** [comment]
Probably this is related to the original issue. The contents of $$$favorites page can be accessed by directly linking that page typing [[$$$favorites]] and clicking the link.

**Comment by logseq-cldwalker** [comment]
@blogbourri Hi. A fix has been pushed to disallow navigating to internal pages like `$$$favorites` and should be up on test in ~10m. Is that sufficient to address the bug or is seeing it in queries also a concern?

**Comment by blogbourri** [comment]
> @blogbourri Hi. A fix has been pushed to disallow navigating to internal pages like `$$$favorites` and should be up on test in ~10m. Is that sufficient to address the bug or is seeing it in queries also a concern?

i think if it's not a page that is navigable, it doesn't make sense to have it clutter the query results, or there should be a way to filter it out of the results (but the latter seems like it'd be overly complicated so i'd lean towards just hiding it always). it can still be opened in the sidebar currently if you type [[$$$favorites]] and shift+click. i think in general stumbling on it is just kinda a confusing user experience.

**Comment by logseq-cldwalker** [comment]
@blogbourri Thanks for pointing out the sidebar. Access to  internal pages from the sidebar has been blocked. As for not cluttering the results, will fix this after we've tackled related tech debt with removing "hidden" pages. No point in fixing this for hidden pages and then redoing it again after tech debt

**Comment by logseq-cldwalker** [comment]
@blogbourri This was fixed by https://github.com/logseq/logseq/pull/11565. Closing but feel free to let us know if you can still reproduce
