### ISSUE TITLE
Journal headers not displaying like proper links

### ISSUE THREAD

**Issue by nckre** [logseq/db-test#93]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Two small issues with https://github.com/logseq/logseq/commit/89cbd131d0073c2a744756eab1fe3572c9bc36a8:

1. Mouse cursor doesn't change to link pointer when hovering over title but still displays an I-beam cursor
2. Deleting text from first node still goes to (uneditable) header text

### Reproduce the Bug

1. Go to first node on Journals
2. Delete text

### Screenshots

![CleanShot 2024-09-16 at 11 19 08](https://github.com/user-attachments/assets/bbcf1c10-aa8e-4c58-8885-f4ed0a93783a)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
@nckre The cursor one has been fixed.
> Deleting text from first node still goes to (uneditable) header text

The ability to edit unmodified nodes is still allowed because it can be used to add tags/properties and make it possible to select them for further actions.
