### ISSUE TITLE
(incorrect?) Order of Search Results

### ISSUE THREAD

**Issue by Bad3r** [logseq/db-test#99]
Lets say for example you have the tag `#A` and the tag `#A/B`. When linking/referencing the tag by typing `#A` the first search option is `#A/B` instead of `#A` which more closely matches the user input.

Example with `#Linux` and `#Linux/Kernel`
![image](https://github.com/user-attachments/assets/9064897c-fbb5-4abc-b540-4e42484e44b6)

This is an issue because of you type `#A` and press enter immediately logseq will convert it to the first option `#A/B` which is IMO not the intended tag.

 

### Reproduce the Bug

1. create two tags `#A` and `#A/B`
2. in a block type `#A` and press enter.
3. the tag `#A` will be interpreted as `#A/B` instead of the intended tag `#A`

Note that this also happens with `#A B` its not exclusive to the slash mark.
![image](https://github.com/user-attachments/assets/8eeb2536-5d9c-420b-b524-cec4620e5d5a)

The order doesn't make sense at all. `A B` is at the top while `A` is at the bottom and others are in the middle.

**Comment by Bad3r** [comment]
here is another example with `#A`, `#A B`, `#A B C` and `#A C B`
![image](https://github.com/user-attachments/assets/8b8addeb-ba2a-43f2-bc31-932dd8e3f442)

**Comment by tiensonqin** [comment]
It should be fixed by https://github.com/logseq/logseq/commit/42f127b3963a660e8eeea97090b35664b9698b99, let me know whether it works for you 🙏
